"""Source-audited internal algorithm records for non-placement ECOS stages."""

from __future__ import annotations


AlgorithmDetail = tuple[str, tuple[str, ...], str, tuple[str, ...]]

SOURCE_PATHS = {
    "yosys.builder": "ecc/chipcompiler/tools/yosys/builder.py",
    "yosys.script": "ecc/chipcompiler/tools/yosys/scripts/yosys_synthesis.tcl",
    "yosys.tech": "ecc/chipcompiler/tools/yosys/scripts/init_tech.tcl",
    "ifp.interface": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/interface/FPInterface.cpp",
    "ifp.die_builder": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/source/module/die_builder/DieBuilder.cpp",
    "ifp.io_placer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/source/module/io_placer/IOPlacer.cpp",
    "ifp.macro_placer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/source/module/macro_placer/MacroPlacer.cpp",
    "ifp.pdn": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/source/module/pdn_generator/PDNGenerator.cpp",
    "ifp.phy_placer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iFP/source/module/phy_placer/PhyPlacer.cpp",
    "izh.filler": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iZH/source/module/filler_inserter/FillerInserter.cpp",
    "icts.api": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/interface/CTSAPI.cc",
    "icts.synthesis": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/source/module/synthesis/Synthesis.cc",
    "icts.topology": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/source/module/synthesis/topology/Topology.cc",
    "icts.htree": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/source/module/synthesis/htree/HTree.cc",
    "icts.router": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/source/module/routing/router/Router.cc",
    "icts.optimization": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iCTS/source/module/optimization/Optimization.cc",
    "dreamplace.basic_place": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/BasicPlace.py",
    "dreamplace.placer": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/Placer.py",
    "dreamplace.nonlinear": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/NonLinearPlace.py",
    "dreamplace.macro_legalize": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/ops/macro_legalize/src/macro_legalize.cpp",
    "dreamplace.greedy_legalize": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/ops/greedy_legalize/src/greedy_legalize_cpu.cpp",
    "dreamplace.abacus_legalize": "ecc/chipcompiler/thirdparty/ecc-dreamplace/dreamplace/ops/abacus_legalize/src/abacus_legalize.cpp",
    "irt.interface": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRT/interface/RTInterface.cpp",
    "irt.planar_router": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRT/source/module/planar_router/PlanarRouter.cpp",
    "irt.layer_assigner": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRT/source/module/layer_assigner/LayerAssigner.cpp",
    "irt.track_assigner": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRT/source/module/track_assigner/TrackAssigner.cpp",
    "irt.detailed_router": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRT/source/module/detailed_router/DetailedRouter.cpp",
    "idrc.interface": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iDRC/interface/DRCInterface.cpp",
    "idrc.validator": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iDRC/source/module/rule_validator/RuleValidator.cpp",
    "idrc.metal_short": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iDRC/source/module/rule_validator/rv_design_rule/MetalShort.cpp",
    "idrc.minimum_width": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iDRC/source/module/rule_validator/rv_design_rule/MinimumWidth.cpp",
    "idrc.cut_spacing": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iDRC/source/module/rule_validator/rv_design_rule/SameLayerCutSpacing.cpp",
    "ircx.topo": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/topo_builder/TopoBuilder.cpp",
    "ircx.env": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/env_builder/EnvBuilder.cpp",
    "ircx.var_processor": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/var_processor/VarProcessor.cpp",
    "ircx.res_extractor": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/res_extractor/ResExtractor.cpp",
    "ircx.cap_extractor": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/cap_extractor/CapExtractor.cpp",
    "ircx.spef_writer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iRCX/source/module/spef_writer/SPEFWriter.cpp",
    "ista.interface": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iSTA/interface/STAInterface.cpp",
    "ista.graph_builder": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iSTA/source/module/graph_builder/GraphBuilder.cpp",
    "ista.propagator": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iSTA/source/module/timing_propagator/TimingPropagator.cpp",
    "ista.analyzer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iSTA/source/module/timing_analyzer/TimingAnalyzer.cpp",
    "ista.characterizer": "ecc/chipcompiler/thirdparty/ecc-tools/src/operation/iSTA/source/module/timing_characterizer/TimingCharacterizer.cpp",
    "idb.python": "ecc/chipcompiler/thirdparty/ecc-tools/src/interface/python/py_idb/py_db.cpp",
    "idb.builder": "ecc/chipcompiler/thirdparty/ecc-tools/src/database/manager/builder/builder.cpp",
}


ALGORITHM_DETAILS: dict[str, tuple[AlgorithmDetail, ...]] = {
    "synthesis": (
        (
            "frontend_lowering",
            ("yosys frontend lowering", "synthesis rtlil graph"),
            "**Input and state:** The generated Tcl selects `read_slang` for a Slang-required file list or `read_verilog -sv` otherwise, then creates Yosys RTLIL modules and processes.\n\n**Algorithm:** `synth -run :fine` elaborates the top module before `share -aggressive`, `onehot`, `muxpack`, `opt_demorgan`, and `opt_ffinv` simplify resource sharing, one-hot logic, multiplexers, De Morgan forms, and inverted flip-flop controls. A second `synth -run fine:` and `opt_clean -purge` remove dead logic before technology mapping.\n\n**Boundary:** This is a finite pass schedule over the imported RTLIL graph; it is not a physical placement or timing signoff result.",
            ("yosys.script",),
        ),
        (
            "technology_mapping",
            ("yosys technology mapping", "abc synthesis optimization"),
            "**Input and state:** The generated global Tcl supplies Liberty cells, dont-use cells, clock period, ABC driver/load, and the selected delay-or-area strategy.\n\n**Algorithm:** Yosys runs `clockgate`, `dfflibmap`, and ABC with `-D` set to the clock period. The ABC script alternates balancing, resubstitution, rewriting, refactoring, retiming, Boolean mapping, buffering, resizing, and static timing estimation; `hilomap` and `setundef -zero` then resolve constants and undefined values.\n\n**Boundary:** Mapping optimizes the gate-level implementation against supplied library constraints. It does not establish that downstream CTS, routing, or extracted timing is clean.",
            ("yosys.script", "yosys.tech"),
        ),
        (
            "constraint_materialization",
            ("yosys global tcl constraints", "synthesis clock period liberty"),
            "**Input and state:** `generate_global_var_tcl()` materializes top-module, RTL/filelist, frequency, Liberty, dont-use, tie-cell, ABC driver/load, and output paths into `global_var.tcl`.\n\n**Algorithm:** It converts frequency to `clk_period_ps = 1000000.0 / clk_freq_mhz`, selects either single RTL or a file list, and serializes mapping constraints consumed by the Tcl pass sequence. Missing top module, frequency, or source input prevents a valid invocation.\n\n**Boundary:** This is deterministic configuration construction. It defines optimization inputs but does not itself transform the netlist.",
            ("yosys.builder",),
        ),
        (
            "mapped_netlist_gate",
            ("yosys mapped netlist check", "synthesis mapped validation"),
            "**Output and gate:** After mapping, the Tcl writes stat JSON, runs `check -mapped`, and writes the final Verilog. The ECOS runner accepts the stage only when `step.output.verilog` exists after the Yosys process returns.\n\n**Failure boundary:** A successful process exit without that declared netlist is invalid synthesis; supplemental netlist STA is attempted only after this gate and does not retroactively prove or invalidate mapping.",
            ("yosys.script", "yosys.runner"),
        ),
    ),
    "floorplan": (
        (
            "database_wrapping",
            ("floorplan database wrapping", "ifp config database"),
            "**Input and state:** `FPInterface::initFP()` parses the Floorplan JSON and wraps the live iDB design/layout into iFP `Config` and `Database` objects containing site, masters, routing layers, instances, nets, and IO pins.\n\n**Algorithm:** The wrapper performs deterministic container conversion before any geometry is generated, so later iFP modules operate on an internal physical model rather than raw JSON.\n\n**Boundary:** The conversion ends after the finite iDB collections have been scanned; it does not synthesize a new logical netlist.",
            ("ifp.interface",),
        ),
        (
            "die_core_rows_tracks",
            ("floorplan die core rows tracks", "die builder utilization"),
            "**Input and state:** `DieBuilder` receives die mode, cell area, aspect ratio/utilization or explicit size, margins, site, and routing-layer pitch/offset.\n\n**Algorithm:** In utilization mode it derives die area and dimensions; otherwise it uses the configured size. It aligns the core to the placement site, enumerates rows at row height, and emits X/Y track grids for routing layers.\n\n**Constraint and stop:** Site alignment and positive track pitch constrain construction. The finite row/layer loops finish with Die, Core, Row, and Track objects stored in the iFP database.",
            ("ifp.die_builder",),
        ),
        (
            "io_pin_placement",
            ("floorplan io pin placement", "io placer edge distribution"),
            "**Input and state:** `IOPlacer` consumes eligible layers, pin width/depth, die/core bounds, preferred routing directions, manufacturing grid, and IO pins.\n\n**Algorithm:** It selects horizontal and vertical layers, distributes pins across four edges using `ceil(num_pins / 4)`, interpolates each edge coordinate, and grid-aligns the generated port rectangle.\n\n**Constraint and stop:** The placer reserves an edge track pitch and falls back to a core/range center when the legal interval is too small. It stops after the finite IO-pin list and writes pin, port, and net-pin coordinates.",
            ("ifp.io_placer",),
        ),
        (
            "macro_halo_row_cutting",
            ("floorplan macro halo row cutting", "macro placement blockage rows"),
            "**Input and state:** Placed macros, core bounds, placement/routing halos, rows, and site dimensions form the macro-placement state.\n\n**Algorithm:** `MacroPlacer` expands macro halos; for each row it gathers intersecting placement-halo blockage intervals, aligns them to sites, sorts them, and emits the remaining legal row segments.\n\n**Constraint and stop:** Only placed macros participate, and out-of-core macros are warnings rather than a relocation optimizer. The finite macro/row traversal replaces the row list with cut rows.",
            ("ifp.macro_placer",),
        ),
        (
            "pdn_and_physical_cells",
            ("floorplan pdn tap endcap generation", "floorplan physical cell insertion"),
            "**Input and state:** PDN global-connect, rails, stripes, layer pairs, macro routing halos, rows, and physical-cell masters are loaded from the Floorplan configuration.\n\n**Algorithm:** The PDN generator builds power nets, rails and stripes, clips wires around macro halos, then adds vias at layer and macro-pin overlaps. `PhyPlacer` builds available regions and inserts side/edge endcaps, well taps, and boundary taps on the site grid.\n\n**Output boundary:** `FPInterface::output()` writes die/core/rows/tracks, special-net wires/vias, IO pins, macros, and new instances back to iDB; all generation loops are finite configuration and geometry traversals.",
            ("ifp.pdn", "ifp.phy_placer", "ifp.interface"),
        ),
    ),
    "cts": (
        (
            "flow_pipeline",
            ("cts internal pipeline", "icts synthesis optimization instantiation evaluation"),
            "**Input and state:** `CTSAPI::runCTS()` initializes a CTS data manager, design, clock layout, and QoR summary from the CTS configuration and work directory.\n\n**Algorithm:** It executes the native pipeline `Synthesis -> Optimization -> Instantiation -> Evaluation` on shared clock-layout state. A not-initialized flow, an internal-stage failure, or an all-clock no-op produces an explicit native status.\n\n**Output boundary:** Key results include buffer count/area, clock-path buffer range, wirelength, and clock-tree level; they are facts of the constructed clock implementation, not final post-route signoff.",
            ("icts.api",),
        ),
        (
            "clock_domain_synthesis",
            ("cts clock domain synthesis", "cts sink partition"),
            "**Input and state:** `Synthesis::run()` iterates design clocks and separates each clock's hard-macro sinks from regular sinks into domain contexts with shared characterization data.\n\n**Algorithm:** Every usable clock source, source net, and sink domain is prepared before `Topology::formClock()` commits a clock topology. Missing clock/source/net/sink/DBU data causes that clock to be skipped or failed; if all clocks are skipped, synthesis is a no-op.\n\n**Output:** The CTS database records inserted buffers/nets, selected H-tree depth/levels, and per-domain status.",
            ("icts.synthesis",),
        ),
        (
            "htree_topology_search",
            ("cts htree topology search", "cts depth candidate search"),
            "**Input and state:** H-tree synthesis receives root-net loads, buffer characterization, boundary constraints, fanout/cap/slew limits, and candidate level plans.\n\n**Algorithm:** It generates a topology, characterizes it, builds level plans, enumerates allowable depths, and evaluates the candidate frontier. Per sink domain, a direct connection is used for fewer than two sinks; otherwise the selected tree is committed before a source-to-root trunk is built.\n\n**Stop:** A feasible candidate is finalized; absent feasible characterization or a failed domain/trunk resets that clock topology rather than claiming a clock tree.",
            ("icts.topology", "icts.htree"),
        ),
        (
            "rc_tree_sizing_optimization",
            ("cts rc tree sizing optimization", "cts post synthesis buffer sizing"),
            "**Input and state:** The router constructs route trees and RC trees for clock DAG nets, then FastSTA supplies resizable-buffer and timing context.\n\n**Algorithm:** Optimization chooses scalable or ordinary sizing solvers, evaluates batch trial master-cell edits, and accepts edits that improve the target objective over skew, capacitance/slew violations, area, and power.\n\n**Stop and output:** No resizable buffer or no accepted candidate is a no-op. Accepted sizing edits are committed into the clock layout and design database.",
            ("icts.router", "icts.optimization"),
        ),
    ),
    "legalization": (
        (
            "legalize_only_setup",
            ("legalization legalize only setup", "dreamplace legalization parameters"),
            "**Input and state:** The standalone legalization runner uses the current ECC-backed DEF/netlist state and forces DreamPlace global placement, fillers, and random-center initialization off while enabling `legalize_flag`.\n\n**Algorithm:** `PlacementEngine.setup_rawdb()` imports the ECC database, builds placement tensors and operators, then invokes `NonLinearPlace` in legalize-only mode.\n\n**Stop:** The engine returns its PPA dictionary; an infinite HPWL is the runner's failure signal, while a finite value is still only auditable with saved stage artifacts.",
            ("dreamplace.module", "dreamplace.placer"),
        ),
        (
            "legalization_pipeline",
            ("dreamplace legalization pipeline", "macro greedy abacus legalization"),
            "**Input and state:** The legalization operators consume the continuous `pos` tensor, node dimensions/weights, fixed objects, placement bounds, site/row geometry, and optional fence regions.\n\n**Algorithm:** For ordinary regions, `NonLinearPlace` composes `MacroLegalize -> GreedyLegalize -> AbacusLegalize`; it checks legality after greedy placement and after Abacus refinement. Fence-region designs use per-region operators before merging.\n\n**Failure boundary:** A failed legality check returns the earlier candidate designated by the implementation; it does not silently mark an illegal result as legalized.",
            ("dreamplace.basic_place", "dreamplace.nonlinear"),
        ),
        (
            "macro_legalization",
            ("dreamplace macro legalization", "macro hannan lp legalization"),
            "**Input and state:** Macro legalization builds `LegalizationDB` from movable and fixed macros, with dummy-fixed filtering and displacement statistics.\n\n**Algorithm:** It first applies rough Hannan legalization to small-overlap clusters, then LP legalization. If legality remains unsatisfied it runs Hannan grid legalization followed by LP refinement, retaining the legal candidate with the best displacement measure.\n\n**Stop:** With no movable macros it returns immediately; otherwise macro/fixed-macro overlap checks decide whether a candidate is accepted.",
            ("dreamplace.macro_legalize",),
        ),
        (
            "greedy_and_abacus_cells",
            ("dreamplace greedy abacus legalization", "standard cell row legalization"),
            "**Input and state:** Standard cells, fixed blockages, row-height bins, blank intervals, and initial positions form the cell-legalization model.\n\n**Algorithm:** Greedy legalization runs left and right passes, assigns cells to bins, subtracts fixed cells into blank intervals, and merges bins while cells remain unplaced. Abacus then sorts cells by row/bin, creates and merges clusters, solves cluster positions from `q/e`, clamps to the bin, aligns to sites, and advances coordinates to prevent overlap.\n\n**Stop and output:** Greedy stops when all cells are placed or no more bin rounds remain; Abacus returns refined movable coordinates after its finite row/bin traversal.",
            ("dreamplace.greedy_legalize", "dreamplace.abacus_legalize"),
        ),
    ),
    "route": (
        (
            "routing_pipeline",
            ("route irt internal pipeline", "irt pin access planar layer track detailed"),
            "**Input and state:** `RTInterface::runRT()` runs on the shared RT database created by `init_rt`, containing routing graph, net list, technology rules, and configuration.\n\n**Algorithm:** The native schedule is `PinAccessor -> SupplyAnalyzer -> PlanarRouter -> LayerAssigner -> TrackAssigner -> DetailedRouter -> ViolationReporter`. Each module consumes and updates shared global/detailed route maps before `destroy_rt` writes results and releases data.\n\n**Boundary:** This sequence is the internal iRT router, not the ECOS runner's later persistence or GUI analysis.",
            ("irt.interface",),
        ),
        (
            "planar_global_routing",
            ("route planar global routing", "irt planar router astar congestion"),
            "**Input and state:** `PlanarRouter` builds `PRModel` nets, pins, planar routing-edge maps, and planar topologies from iRT data.\n\n**Algorithm:** It initializes with L/Z patterns, runs congestion-aware L/Z and overflow all-pattern routing, then rip-up/reroutes overflow nets with A* for at most five iterations. Candidate cost combines wirelength, edge cost, and corner cost; edge penalties use supply/demand, overflow, saturation, and hotspot terms.\n\n**Stop and output:** The router stops when no overflow nets remain or the iteration bound is exhausted, then writes `net_global_result_map` and rebuilds spatial indexes.",
            ("irt.planar_router",),
        ),
        (
            "layer_assignment",
            ("route layer assignment", "irt tree dynamic programming"),
            "**Input and state:** `LayerAssigner` converts planar results into `LAModel` pillar trees with candidate routing layers, per-layer edge supply, and direction constraints.\n\n**Algorithm:** It performs bottom-up dynamic programming over subtree layer candidates, then top-down assignment fixes child layers. The cost combines required via span and segment overflow; routing layers are limited by the configured bottom/top range and preferred direction.\n\n**Stop and output:** Overflow segments trigger a planar-tree split and one rebuild. The result is a 3D routing tree and updated global-route map.",
            ("irt.layer_assigner",),
        ),
        (
            "track_assignment",
            ("route track assignment", "irt panel astar track router"),
            "**Input and state:** `TrackAssigner` partitions `TAModel` into layer panels containing track axes, nodes, neighbors, tasks, and R-tree environment.\n\n**Algorithm:** Scheduled panels are processed in parallel. Each task uses an open-queue search bounded by its task box; cost includes fixed/routed rectangles, violation penalty, and preferred-wire, via, and estimated-to-end terms.\n\n**Stop and output:** A task stops when all end groups connect. Panel results update detailed-route and patch maps for detailed routing.",
            ("irt.track_assigner",),
        ),
        (
            "detailed_routing_and_patch",
            ("route detailed routing patch", "irt detailed router drc repair"),
            "**Input and state:** `DetailedRouter` uses `DRModel`, scheduled `DRBox` regions, `DRTask` routing groups, guide penalties, and route-violation state.\n\n**Algorithm:** Nine detailed-routing iteration parameter sets repeatedly route dirty boxes in parallel, reroute net schedules, and use multi-source A* to connect task endpoint groups. Costs include preferred/non-preferred wire, bend, via, guide, fixed/routed-shape, and violation penalties. DRC-driven patch tasks search candidate patches and retain the best result.\n\n**Stop and output:** `stopIteration()` or exhaustion selects the best result, then updates detailed segments, patches, and violations. A completed router is not equivalent to zero remaining DRC violations.",
            ("irt.detailed_router",),
        ),
    ),
    "drc": (
        (
            "shape_collection",
            ("drc shape collection", "idrc environment result shapes"),
            "**Input and state:** DRC reads iDB layout, instances, pins, IO pins, blockages, regular nets, and special nets into environment and result `ids::Shape` collections.\n\n**Algorithm:** Environment collection includes instance OBS/pins/vias, IO pins, and routing blockages; result collection converts routed segments, vias, and rectangles. Unplaced instances and nets without valid multi-terminal connectivity are skipped, while blockage polygons subtract pin shapes before max-rectangle decomposition.\n\n**Stop and output:** Finite design-container traversal returns the shape vectors supplied to rule validation.",
            ("idrc.interface",),
        ),
        (
            "cluster_partitioning",
            ("drc cluster partitioning", "idrc rule validator grid clusters"),
            "**Input and state:** `RuleValidator` receives environment/result shapes, enabled check types, and optional check regions in an `RVModel`.\n\n**Algorithm:** It derives cluster and expansion sizes from the routing pitch, grids the effective bounding box, and inserts each expanded shape reference into overlapping `RVCluster` cells.\n\n**Constraint and stop:** Negative result-net indices are errors. Partitioning ends after every shape is assigned to its covering clusters.",
            ("idrc.validator",),
        ),
        (
            "geometric_rule_dispatch",
            ("drc geometric rule dispatch", "idrc rtree rule checking"),
            "**Input and state:** Each cluster builds per-layer polygon sets, maximum rectangles, boundary data, and rectangle/boundary/cut R-trees.\n\n**Algorithm:** Clusters run in parallel when they contain relevant result shapes. The validator dispatches only enabled and existing rule types, querying those indexes against rule-specific geometry.\n\n**Boundary:** Spatial partitioning controls work locality; it does not omit violations outside a cluster because expanded shape coverage is included before checking.",
            ("idrc.validator",),
        ),
        (
            "violation_generation_and_merge",
            ("drc metal short width cut spacing", "idrc violation merge"),
            "**Algorithm:** Representative checks detect different-net routing-rectangle overlap for metal shorts, insufficient polygon span for minimum width, and nearby cuts using same-net/PRL/spacing rules. Each records a typed violation with required geometry.\n\n**Stop and output:** Cluster post-processing keeps only violations overlapping the cluster region, then sorts and deduplicates. The global list is sorted/uniqued before it is exported as reports and feature facts; an absent feature file must not be interpreted as an empty violation list.",
            ("idrc.metal_short", "idrc.minimum_width", "idrc.cut_spacing", "idrc.validator"),
        ),
    ),
    "filler": (
        (
            "filler_model_initialization",
            ("filler model initialization", "izh filler rows masters"),
            "**Input and state:** The native filler insertion path builds an `FIModel` from iDB rows, cell masters, `-filler` configuration, and `-min_filler_width`.\n\n**Algorithm:** It filters invalid or non-horizontal rows and accepts only core-filler masters whose widths are site-width multiples, then sorts masters by descending width.\n\n**Constraint and stop:** A non-positive minimum width is invalid. Initialization ends with rows, sorted master choices, and insertion counters; it does not yet modify the design.",
            ("izh.filler",),
        ),
        (
            "available_segment_extraction",
            ("filler available segments", "filler blockage site bitmap"),
            "**Input and state:** Each `FIRow` begins with a site-availability bitmap. Placed instance boxes and placement-blockage rectangles are clipped to intersecting rows.\n\n**Algorithm:** Blockages are converted to clamped site-index ranges and marked unavailable, then the bitmap is scanned into contiguous `FISegment` gaps.\n\n**Stop and output:** The finite blockage and row scans produce the legal segments in which filler cells may be inserted.",
            ("izh.filler",),
        ),
        (
            "greedy_segment_packing",
            ("filler greedy packing", "filler largest first packing"),
            "**Input and state:** A legal segment, descending-width filler masters, and the minimum filler-site count form one packing problem.\n\n**Algorithm:** Starting at the segment's left site, the inserter picks the first master that fits while leaving either zero remainder or a remainder at least as large as the minimum filler width.\n\n**Stop and output:** Packing stops when no master can be added or the remaining sites are too few. This largest-first greedy policy avoids an unfillable sub-minimum gap but does not solve a global optimal packing problem.",
            ("izh.filler",),
        ),
        (
            "instance_writeback",
            ("filler instance writeback", "filler placed instance creation"),
            "**Algorithm:** For each selected master, `addFillerInstance()` computes `origin_x + begin_site_idx * site_width`, keeps the row orientation, creates a unique instance name, and writes a placed filler instance to iDB.\n\n**Constraint and stop:** Missing design/master data prevents insertion; name collisions are handled by unique-name generation and error-on-existing creation. Counters advance for each created instance, then ECOS serializes the resulting database.",
            ("izh.filler",),
        ),
    ),
    "rcx": (
        (
            "topology_construction",
            ("rcx topology construction", "ircx topo pool nodes edges"),
            "**Input and state:** RCX converts regular-net segments/vias and special-net segments/patches into `TopoPool` nodes and edges.\n\n**Algorithm:** Each regular net builds local `TBTopo` nodes from segment/via endpoints and edges from the corresponding geometry, then normalizes local indexes into the global pool. Pin membership is tested against pin-layer shapes; unmatched points receive a small fallback shape, while special nets contribute special edges.\n\n**Stop and output:** Parallel finite net traversal produces the regular node/edge pools and special-edge list used by extraction.",
            ("ircx.topo",),
        ),
        (
            "environment_overlap_model",
            ("rcx environment overlap model", "ircx track pixel adjacency"),
            "**Input and state:** `EnvBuilder` combines the topology pool with routing tracks and die geometry into track and pixel indexes.\n\n**Algorithm:** For each non-via edge it queries adjacent-track overlap, merges intervals, then queries cross-layer pixel overlap and clips it to those intervals. Via edges retain placeholders to preserve index correspondence.\n\n**Boundary:** The resulting `NetEnv` records local conductor surroundings; it is not yet a resistance or capacitance value.",
            ("ircx.env",),
        ),
        (
            "corner_effective_geometry",
            ("rcx corner effective geometry", "ircx etch profile"),
            "**Input and state:** Process-conductor tables, `NetEnv`, and topology edges are expanded into per-corner `NetEtchProfile` records.\n\n**Algorithm:** For every corner/net/edge, RCX queries lower and upper adjacent spacing against etch tables and adjusts edge center and width over each interval. Via edges and missing process conductors are skipped.\n\n**Stop and output:** The finite corner/net/edge traversal leaves effective geometry for electrical extraction rather than modifying routed geometry.",
            ("ircx.var_processor",),
        ),
        (
            "resistance_extraction",
            ("rcx resistance extraction", "ircx wire via resistance"),
            "**Input and state:** Topology edges, corner process conductors/vias, and etch profiles feed per-corner `RCData` resistance lists.\n\n**Algorithm:** Wire-edge overlap lengths are accumulated using resistivity or sheet resistance and a temperature factor; via resistance is obtained from via-shape area and process-via data. Invalid width/thickness or absent process records are skipped.\n\n**Stop and output:** The extractor completes after all corner/net/edge records are handled and leaves per-corner resistance facts for SPEF writing.",
            ("ircx.res_extractor",),
        ),
        (
            "capacitance_and_spef",
            ("rcx capacitance spef writing", "ircx coupling ground capacitance"),
            "**Input and state:** Edge environment intervals, etch profiles, capacitance tables, coupling references, and topology nodes/edges form the capacitance model.\n\n**Algorithm:** RCX splits cross-layer spans, selects above/below capacitance tables, interpolates by spacing, and emits ground or coupling capacitance. The SPEF writer assigns edge capacitance to nodes and writes `*CONN`, `*CAP`, and `*RES`, merging coupling entries.\n\n**Boundary:** Via edges do not receive capacitance; missing conductor/table data is skipped. Completion means declared per-corner SPEFs have been written, not that every expected corner exists.",
            ("ircx.cap_extractor", "ircx.spef_writer"),
        ),
    ),
    "sta": (
        (
            "signoff_matrix_expansion",
            ("sta signoff matrix expansion", "sta liberty rcx corner matrix"),
            "**Input and state:** `collect_sta_signoff_items()` expands the STA configuration's Liberty corners and their listed RCX corners into records containing corner name, temperature, Liberty files, and SPEF path.\n\n**Algorithm:** It constructs the complete Cartesian-like configured signoff list before timing runs. Every requested Liberty corner must resolve; missing configuration is an incomplete-analysis condition rather than a silently dropped corner.\n\n**Output:** The matrix preserves the intended multi-corner coverage used by later aggregation.",
            ("ecc.runner",),
        ),
        (
            "native_setup_and_graph_build",
            ("sta native graph build", "ista timing graph construction"),
            "**Input and state:** For each item, the wrapper validates report/feature destinations, clears old outputs, loads Liberty/SDC/SPEF, and initializes native STA with the requested corner and path limit.\n\n**Algorithm:** `GraphBuilder` builds timing points, cell arcs, net driver/load relations, net arcs, start/end points, and a topological timing order. Native execution then proceeds through clock, timing, and power propagation before reporting.\n\n**Failure boundary:** Required SDC, SPEF, Liberty, or output directories are validated before a corner is considered analyzed.",
            ("ecc.module", "ista.interface", "ista.graph_builder"),
        ),
        (
            "timing_propagation",
            ("sta timing propagation", "ista arrival slew propagation"),
            "**Input and state:** The graph's topological timing order, arcs, cell delays, net parasitics, and clock state define propagation.\n\n**Algorithm:** `TimingPropagator` traverses timing order, propagating slew, delay, arrival, and path state while skipping disabled arcs and sequential clock sinks. Clock propagation establishes timing references before data propagation.\n\n**Stop and output:** The finite graph order determines completion; propagated state becomes the input to required-time and violation analysis.",
            ("ista.interface", "ista.propagator"),
        ),
        (
            "required_time_and_qor_analysis",
            ("sta required time analysis", "ista wns tns timing paths"),
            "**Algorithm:** `TimingAnalyzer` works from endpoints backward to derive required timing, groups timing paths, and updates WNS, TNS, and violation counts. ECOS then selects the minimum setup/hold WNS/TNS and minimum frequency across available corners while retaining coverage facts.\n\n**Boundary:** A worst-corner aggregate is derived only from loaded results. It must preserve missing configured corners instead of treating them as zero slack or successful signoff.",
            ("ista.analyzer", "ecc.runner"),
        ),
    ),
    "harden": (
        (
            "delivery_input_selection",
            ("harden delivery input selection", "harden first signoff item"),
            "**Input and state:** Harden resolves the STA signoff matrix and deliberately selects its first item, which supplies Liberty, SDC, and SPEF inputs for the timing-model extraction.\n\n**Algorithm:** It emits abstract LEF, timing-model LIB, and hardened GDS in that order. An empty signoff matrix terminates before any package artifact is generated.\n\n**Boundary:** This is a deterministic packaging choice, not multi-corner model merging; the selected first item must remain visible in provenance.",
            ("ecc.runner",),
        ),
        (
            "abstract_lef_generation",
            ("harden abstract lef generation", "idb save lef macro abstraction"),
            "**Input and state:** The current in-memory iDB design and declared LEF output path are passed through the Python binding to native `saveLef()`.\n\n**Algorithm:** The native database writer serializes the block's LEF macro abstraction from the current physical database. There is no placement or routing optimization in this export.\n\n**Stop and output:** Native writer success yields the abstract LEF; package completion still requires the separate LIB and GDS artifacts.",
            ("idb.python",),
        ),
        (
            "timing_model_characterization",
            ("harden timing model characterization", "ista extract lib timing characterizer"),
            "**Input and state:** The selected Liberty, SDC, SPEF, STA configuration, design name, and output directory initialize native STA for timing-model extraction.\n\n**Algorithm:** `extractLib()` builds and propagates the timing graph, analyzes timing, then `TimingCharacterizer::characterize()` writes the derived model. The wrapper locates the generated analysis-mode LIB and copies it to the Harden output.\n\n**Failure boundary:** Missing or ambiguous generated source LIB raises an error; an empty generated model receives only the implementation's minimal fallback library shell.",
            ("ecc.module", "ista.interface", "ista.characterizer"),
        ),
        (
            "hardened_gds_export",
            ("harden hardened gds export", "idb write hardened db"),
            "**Input and state:** The current DEF/iDB layout and declared GDS path are passed to `gds_save(..., is_harden=True)`.\n\n**Algorithm:** The native builder initializes the DEF writer, constructs `Def2GdsWrite`, and selects `writeHardenedDb()` rather than the ordinary `writeDb()` path.\n\n**Stop and output:** Writer initialization failure returns false; successful GDS export alone is insufficient because delivery completion also checks the LEF and LIB package members.",
            ("idb.builder",),
        ),
    ),
}
