import { describe, expect, it } from 'vitest'
import source from './ProjectQorTrendPanel.vue?raw'

describe('ProjectQorTrendPanel', () => {
  it('renders the embedded QoR overview score chart and delta card', () => {
    expect(source).toContain('QoR Overview')
    expect(source).not.toContain('QoR Trend')
    expect(source).toContain('Overall Score')
    expect(source).toContain('Top Regressions')
    expect(source).toContain('Baseline:')
    expect(source).toContain('baselineLabel')
    expect(source).toContain('baselineWorkspaceId')
    expect(source).toContain('ri-download-line')
    expect(source).toContain("'export-report'")
    expect(source).toContain('ri-flag-line')
    expect(source).toContain("'set-baseline'")
    expect(source).toContain('setSelectedWorkspaceAsBaseline')
    expect(source).toContain('scoreTicks')
    expect(source).toContain('qor-chart-gridline')
    expect(source).toContain('threshold')
    expect(source).toContain('qor-chart-axis')
    expect(source).toContain('qor-chart-y-axis')
    expect(source).toContain('qor-chart-x-axis')
    expect(source).toContain('qor-chart-point')
    expect(source).toContain('qor-chart-best-ring')
    expect(source).toContain('highestTrendScore')
    expect(source).toContain('qor-chart-workspace-label')
    expect(source).toContain('role="tablist"')
    expect(source).toContain('activeDeltaTab')
    expect(source).not.toContain('Missing Analysis')
    expect(source).not.toContain('Selected Workspace')
    expect(source).not.toContain('unsupportedModules')
    expect(source).not.toContain('qor-trend-points')
  })

  it('keeps the plot boundary and point hierarchy visually distinct', () => {
    expect(source).toContain('stroke-dasharray: 3.5 2.5')
    expect(source).toContain('font-size: 4.2px')
    expect(source).toContain('font-size: 3.9px')
    expect(source).toContain('.qor-chart-point.best')
    expect(source).toContain('.qor-chart-score-label.threshold')
  })

  it('uses prepared QoR model data instead of reading project files directly', () => {
    expect(source).toContain('qorTrendSummary')
    expect(source).not.toContain('readOptionalProjectTextFile')
    expect(source).not.toContain('feature/')
    expect(source).not.toContain('output/')
  })

  it('keeps export and baseline actions without making trend points selectable', () => {
    expect(source).toContain('defineEmits')
    expect(source).toContain('exportReport')
    expect(source).toContain('setSelectedWorkspaceAsBaseline')
    expect(source).not.toContain("'select-point'")
    expect(source).not.toContain('selectTrendPoint')
  })

  it('keeps the delta list scrollable while the chart fills its viewport', () => {
    expect(source).not.toContain('.slice(0, 4)')
    expect(source).toContain('qor-scroll-list')
    expect(source).toContain('class="qor-delta-list qor-scroll-list"')
    expect(source).toContain('qor-chart-viewport')
    expect(source).toContain('ref="chartViewport"')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('width: 100%;')
    expect(source).toContain('grid-template-rows:')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('overflow: auto;')
    expect(source).toContain('min-height: 0;')
  })

  it('uses workspace names and shortens axis labels beyond eight characters', () => {
    expect(source).toContain('shortenWorkspaceLabel(point.label)')
    expect(source).toContain('const maxLength = 8')
    expect(source).toContain('`${label.slice(0, maxLength)}...`')
    expect(source).toContain('<title>{{ point.label }}</title>')
  })

  it('anchors the full-width score chart at the bottom-left plot origin', () => {
    expect(source).toContain('new ResizeObserver')
    expect(source).toContain('chartCoordinateWidth')
    expect(source).toContain('chartViewportSize')
    expect(source).toContain('? chartLeft')
    expect(source).toContain('workspaceLabelAnchor(index, scoreChartPoints.length)')
    expect(source).not.toContain('chartLeft + plotWidth / 2')
  })

  it('uses workspace names instead of internal IDs in QoR delta details', () => {
    expect(source).toContain('delta.workspaceName')
    expect(source).toContain('delta.baselineWorkspaceName')
    expect(source).not.toContain("'message' in delta ? delta.message : delta.workspaceId")
  })

  it('surfaces structured analysis risks in a dedicated scrollable tab', () => {
    expect(source).toContain('Analysis Risks')
    expect(source).toContain("activeDeltaTab.value === 'risks'")
    expect(source).toContain('props.qorTrendSummary.risks')
    expect(source).toContain('Structured analysis and data quality')
    expect(source).toContain('qor-risk-critical')
    expect(source).toContain('qor-risk-warning')
  })

  it('uses a continuous right-edge spine for timing closure and selects its workspace', () => {
    expect(source).toContain('Timing Closure')
    expect(source).toContain("abbreviation: 'IMP'")
    expect(source).toContain("abbreviation: 'REG'")
    expect(source).toContain("abbreviation: 'RISK'")
    expect(source).toContain("abbreviation: 'STA'")
    expect(source).toContain('aria-orientation="vertical"')
    expect(source).toContain('qor-delta-edge-rail')
    expect(source).toContain('qor-vertical-tab')
    expect(source).toContain('qor-vertical-tab-tooltip')
    expect(source).toContain('writing-mode: vertical-rl')
    expect(source).toContain('text-orientation: upright')
    expect(source).toContain('qor-vertical-tab-badge')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr) 38px')
    expect(source).toContain('.qor-vertical-tab + .qor-vertical-tab')
    expect(source).toContain('.qor-vertical-tab.selected::before')
    expect(source).toContain("'select-workspace'")
    expect(source).toContain('selectTimingIssueWorkspace(issue.workspaceId)')
    expect(source).toContain('timingClosure.issues')
    expect(source).toContain('timingClosure.coverage')
    expect(source).toContain('timingClosure.triage')
    expect(source).toContain('visibleTimingIssues')
    expect(source).toContain('currentTriageIssueKeys')
    expect(source).toContain('clearedTimingTriage')
    expect(source).toContain('timingWorkItemCount')
    expect(source).toContain('formatMissingCornerCount(coverage.missingCornerCount)')
    expect(source).toContain('formatAvailableArtifactCount(coverage.availableArtifactCount)')
    expect(source).toContain('formatTimingClockDelays(issue)')
    expect(source).toContain('formatTimingTriage(issue)')
    expect(source).toContain('formatTimingPhysicalContext(issue)')
    expect(source).toContain('Observed physical changes:')
    expect(source).toContain('formatTimingReviewHints(issue)')
    expect(source).toContain('Review next:')
    expect(source).toContain('timingTriageLabel(issue)')
    expect(source).toContain('CLEARED')
    expect(source).toContain('Launch ${launch.toFixed(3)} ns')
    expect(source).toContain('Capture ${capture.toFixed(3)} ns')
    expect(source).not.toContain('qor-delta-tabs')
  })

  it('keeps baseline and export actions in the embedded overview header', () => {
    expect(source).toContain('qor-overview-header')
    expect(source).toContain('qor-baseline-button')
    expect(source).toContain('qor-export-button')
    expect(source).not.toContain('qor-summary-grid')
  })
})
