export const desktopApiIpcChannels = {
  appGetVersions: 'app:get-versions',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  windowConfirmClose: 'window:confirm-close',
  windowSetTitle: 'window:set-title',
  windowIsMaximized: 'window:is-maximized',
  windowCreate: 'window:create',
  workspaceOpenOrFocus: 'workspace:open-or-focus',
  workspaceBindWindow: 'workspace:bind-window',
  workspaceUnbindWindow: 'workspace:unbind-window',
  workspaceGetBoundPath: 'workspace:get-bound-path',
  menuSetActionEnabled: 'menu:set-action-enabled',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsDelete: 'settings:delete',
  projectManifestMutate: 'project-manifest:mutate',
  dialogPickDirectory: 'dialog:pick-directory',
  dialogPickFiles: 'dialog:pick-files',
  dialogPickRtlSources: 'dialog:pick-rtl-sources',
  dialogSaveFile: 'dialog:save-file',
  workspaceIsProjectDirectory: 'workspace:is-project-directory',
  workspaceRegisterProjectRoot: 'workspace:register-project-root',
  workspaceClearProjectRoot: 'workspace:clear-project-root',
  workspaceRequestProjectPathAccess: 'workspace:request-project-path-access',
  workspaceAuthorizeWaveform: 'workspace:authorize-waveform',
  workspaceReadProjectTextFile: 'workspace:read-project-text-file',
  workspaceReadOptionalProjectTextFile: 'workspace:read-optional-project-text-file',
  workspaceReadProjectTextFileTail: 'workspace:read-project-text-file-tail',
  workspaceReadOptionalProjectTextFileTail:
    'workspace:read-optional-project-text-file-tail',
  workspaceReadOptionalProjectTextFileUpdate:
    'workspace:read-optional-project-text-file-update',
  workspaceSubscribeProjectLogTail: 'workspace:subscribe-project-log-tail',
  workspaceUnsubscribeProjectLogTail: 'workspace:unsubscribe-project-log-tail',
  workspaceReadProjectBinaryFile: 'workspace:read-project-binary-file',
  workspaceWriteProjectTextFile: 'workspace:write-project-text-file',
  workspaceListProjectDirectory: 'workspace:list-project-directory',
  workspacePrepareProjectDirectoryReplacement:
    'workspace:prepare-project-directory-replacement',
  workspaceRestoreProjectDirectoryReplacement:
    'workspace:restore-project-directory-replacement',
  workspaceFinalizeProjectDirectoryReplacement:
    'workspace:finalize-project-directory-replacement',
  workspaceRetainProjectDirectoryReplacement:
    'workspace:retain-project-directory-replacement',
  workspaceScanPdkDirectory: 'workspace:scan-pdk-directory',
  workspaceScanRtlDirectory: 'workspace:scan-rtl-directory',
  workspaceListDesignFiles: 'workspace:list-design-files',
  workspaceAddDesignFiles: 'workspace:add-design-files',
  workspaceRemoveDesignFile: 'workspace:remove-design-file',
  workspaceWatchProjectFile: 'workspace:watch-project-file',
  workspaceUnwatchProjectFile: 'workspace:unwatch-project-file',
  workspaceResourcesGetIndex: 'workspace-resources:get-index',
  workspaceResourcesReadHome: 'workspace-resources:read-home',
  workspaceResourcesReadFlow: 'workspace-resources:read-flow',
  workspaceResourcesReadParameters: 'workspace-resources:read-parameters',
  workspaceResourcesResolveStepInfo: 'workspace-resources:resolve-step-info',
  resourcesList: 'resources:list',
  resourcesGet: 'resources:get',
  resourcesReadMpcSpec: 'resources:read-mpc-spec',
  resourcesInstall: 'resources:install',
  resourcesUpdate: 'resources:update',
  resourcesCancel: 'resources:cancel',
  resourcesUninstall: 'resources:uninstall',
  resourcesActivatePdk: 'resources:activate-pdk',
  resourcesValidatePdk: 'resources:validate-pdk',
  resourcesRemovePdkReference: 'resources:remove-pdk-reference',
  resourcesImportPdkPath: 'resources:import-pdk-path',
  resourcesImportLocalPath: 'resources:import-local-path',
  resourcesRefreshRegistry: 'resources:refresh-registry',
  resourcesCheckUpdates: 'resources:check-updates',
  designRuntimeCancel: 'design-runtime:cancel',
  designRuntimeRpcHello: 'design-runtime:rpc-hello',
  designRuntimeRpcPing: 'design-runtime:rpc-ping',
  designRuntimeRpcShutdown: 'design-runtime:rpc-shutdown',
  designRuntimeFrontendCatalog: 'design-runtime:frontend-catalog',
  designRuntimeFrontendValidateConfig: 'design-runtime:frontend-validate-config',
  designRuntimeWorkspaceCreate: 'design-runtime:workspace-create',
  designRuntimeWorkspaceOpen: 'design-runtime:workspace-open',
  designRuntimeWorkspaceClose: 'design-runtime:workspace-close',
  designRuntimeWorkspaceHome: 'design-runtime:workspace-home',
  designRuntimeWorkspaceInfo: 'design-runtime:workspace-info',
  designRuntimeWorkspaceRefreshConfig: 'design-runtime:workspace-refresh-config',
  designRuntimeWorkspaceSyncConfig: 'design-runtime:workspace-sync-config',
  designRuntimeWorkspaceResetFlow: 'design-runtime:workspace-reset-flow',
  designRuntimeFlowRun: 'design-runtime:flow-run',
  designRuntimeFlowRunStep: 'design-runtime:flow-run-step',
  chipViewerOpen: 'chip-viewer:open',
  eccRpcHello: 'ecc:rpc-hello',
  eccRpcPing: 'ecc:rpc-ping',
  eccRpcShutdown: 'ecc:rpc-shutdown',
  eccWorkspaceCreate: 'ecc:workspace-create',
  eccWorkspaceOpen: 'ecc:workspace-open',
  eccWorkspaceClose: 'ecc:workspace-close',
  eccWorkspaceHome: 'ecc:workspace-home',
  eccWorkspaceInfo: 'ecc:workspace-info',
  eccWorkspaceRefreshConfig: 'ecc:workspace-refresh-config',
  eccWorkspaceSyncConfig: 'ecc:workspace-sync-config',
  eccWorkspaceResetFlow: 'ecc:workspace-reset-flow',
  eccWorkspaceExportSignoff: 'ecc:workspace-export-signoff',
  eccWorkspaceInspectSignoff: 'ecc:workspace-inspect-signoff',
  eccFlowRun: 'ecc:flow-run',
  eccFlowRunStep: 'ecc:flow-run-step',
  shellCreateSession: 'shell:create-session',
  shellWrite: 'shell:write',
  shellResize: 'shell:resize',
  shellKill: 'shell:kill',
  systemOpenExternal: 'system:open-external',
} as const

export const desktopApiEventChannels = {
  menuAction: 'menu:action',
  windowCloseRequested: 'window:close-requested',
  windowResized: 'window:resized',
  windowMaximizedChanged: 'window:maximized-changed',
  workspaceFileChanged: 'workspace:file-changed',
  workspaceLogTail: 'workspace:log-tail',
  resourcesProgress: 'resources:progress',
  designRuntimeEvent: 'design-runtime:event',
  eccEvent: 'ecc:event',
  shellData: 'shell:data',
  shellExit: 'shell:exit',
} as const

export type DesktopApiIpcChannel =
  (typeof desktopApiIpcChannels)[keyof typeof desktopApiIpcChannels]

export type DesktopApiEventChannel =
  (typeof desktopApiEventChannels)[keyof typeof desktopApiEventChannels]
