export const desktopApiIpcChannels = {
  appGetVersions: 'app:get-versions',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  windowSetTitle: 'window:set-title',
  windowIsMaximized: 'window:is-maximized',
  windowSetZoomFactor: 'window:set-zoom-factor',
  windowCreate: 'window:create',
  shutdownGetStatus: 'shutdown:get-status',
  shutdownCancel: 'shutdown:cancel',
  shutdownReviewOptions: 'shutdown:review-options',
  shutdownCompleteCleanup: 'shutdown:complete-cleanup',
  workspaceOpenOrFocus: 'workspace:open-or-focus',
  workspacePrepareFlowAgentRerun: 'workspace:prepare-flow-agent-rerun',
  workspaceExecuteFlowAgentRerun: 'workspace:execute-flow-agent-rerun',
  workspaceBindWindow: 'workspace:bind-window',
  workspaceUnbindWindow: 'workspace:unbind-window',
  workspaceGetBoundPath: 'workspace:get-bound-path',
  menuSetActionEnabled: 'menu:set-action-enabled',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsDelete: 'settings:delete',
  projectManifestMutate: 'project-manifest:mutate',
  projectManagementDiscoverProject: 'project-management:discover-project',
  projectManagementReadManifest: 'project-management:read-manifest',
  projectManagementListEntries: 'project-management:list-entries',
  projectManagementReadWorkspaceTexts: 'project-management:read-workspace-texts',
  projectManagementReadWorkspaceStepConfiguration:
    'project-management:read-workspace-step-configuration',
  backendWorkspaceGetOverview: 'backend-workspace:get-overview',
  backendWorkspaceGetArtifact: 'backend-workspace:get-artifact',
  backendWorkspaceGetStepDetail: 'backend-workspace:get-step-detail',
  backendWorkspaceRefreshOverview: 'backend-workspace:refresh-overview',
  backendProjectComparisonSelectProject: 'backend-project-comparison:select-project',
  backendProjectComparisonCloseProject: 'backend-project-comparison:close-project',
  backendProjectComparisonGetComparison: 'backend-project-comparison:get-comparison',
  backendProjectComparisonGetExecutionSnapshot:
    'backend-project-comparison:get-execution-snapshot',
  backendProjectComparisonGetStepFindings: 'backend-project-comparison:get-step-findings',
  backendProjectComparisonRefreshComparison:
    'backend-project-comparison:refresh-comparison',
  dialogPickDirectory: 'dialog:pick-directory',
  dialogPickFiles: 'dialog:pick-files',
  dialogPickRtlSources: 'dialog:pick-rtl-sources',
  dialogSaveFile: 'dialog:save-file',
  workspaceIsProjectDirectory: 'workspace:is-project-directory',
  workspaceRegisterProjectRoot: 'workspace:register-project-root',
  workspaceRegisterProjectReadRoot: 'workspace:register-project-read-root',
  workspaceClearProjectRoot: 'workspace:clear-project-root',
  workspaceRequestProjectPathAccess: 'workspace:request-project-path-access',
  workspaceAuthorizeWaveform: 'workspace:authorize-waveform',
  workspaceOpenWaveformExternal: 'workspace:open-waveform-external',
  workspaceReadProjectTextFile: 'workspace:read-project-text-file',
  workspaceReadOptionalProjectTextFile: 'workspace:read-optional-project-text-file',
  workspaceReadProjectTextFileTail: 'workspace:read-project-text-file-tail',
  workspaceReadOptionalProjectTextFileTail:
    'workspace:read-optional-project-text-file-tail',
  workspaceReadOptionalProjectTextFileChunk:
    'workspace:read-optional-project-text-file-chunk',
  workspaceReadProjectBinaryFile: 'workspace:read-project-binary-file',
  workspaceWriteProjectTextFile: 'workspace:write-project-text-file',
  workspaceListProjectDirectory: 'workspace:list-project-directory',
  workspacePathExists: 'workspace:path-exists',
  workspaceDiscardFailedWorkspaceCreate: 'workspace:discard-failed-workspace-create',
  workspacePrepareProjectDirectoryReplacement:
    'workspace:prepare-project-directory-replacement',
  workspaceRestoreProjectDirectoryReplacement:
    'workspace:restore-project-directory-replacement',
  workspaceFinalizeProjectDirectoryReplacement:
    'workspace:finalize-project-directory-replacement',
  workspaceRetainProjectDirectoryReplacement:
    'workspace:retain-project-directory-replacement',
  workspaceScanPdkDirectory: 'workspace:scan-pdk-directory',
  workspaceScanRtlDirectory: 'workspace:scan-rtl-directory',
  workspaceDiscoverHdlModules: 'workspace:discover-hdl-modules',
  workspaceListDesignFiles: 'workspace:list-design-files',
  workspaceAddDesignFiles: 'workspace:add-design-files',
  workspaceRemoveDesignFile: 'workspace:remove-design-file',
  workspaceResourcesGetIndex: 'workspace-resources:get-index',
  workspaceResourcesReadHome: 'workspace-resources:read-home',
  workspaceResourcesReadFlow: 'workspace-resources:read-flow',
  workspaceResourcesReadParameters: 'workspace-resources:read-parameters',
  workspaceResourcesResolveStepInfo: 'workspace-resources:resolve-step-info',
  resourcesList: 'resources:list',
  resourcesGet: 'resources:get',
  resourcesReadMpcSpec: 'resources:read-mpc-spec',
  resourcesInstall: 'resources:install',
  resourcesUpdate: 'resources:update',
  resourcesCancel: 'resources:cancel',
  resourcesUninstall: 'resources:uninstall',
  resourcesValidatePdk: 'resources:validate-pdk',
  resourcesRemovePdkReference: 'resources:remove-pdk-reference',
  resourcesImportPdkPath: 'resources:import-pdk-path',
  resourcesImportLocalPath: 'resources:import-local-path',
  resourcesRefreshRegistry: 'resources:refresh-registry',
  resourcesCheckUpdates: 'resources:check-updates',
  pdkInventoryList: 'pdk-inventory:list',
  pdkInventoryImport: 'pdk-inventory:import',
  pdkInventoryLocate: 'pdk-inventory:locate',
  pdkInventoryRemove: 'pdk-inventory:remove',
  pdkInventoryResolveBinding: 'pdk-inventory:resolve-binding',
  designRuntimeCancel: 'design-runtime:cancel',
  designRuntimeRpcHello: 'design-runtime:rpc-hello',
  designRuntimeRpcPing: 'design-runtime:rpc-ping',
  designRuntimeRpcShutdown: 'design-runtime:rpc-shutdown',
  designRuntimeFrontendCatalog: 'design-runtime:frontend-catalog',
  designRuntimeFrontendValidateConfig: 'design-runtime:frontend-validate-config',
  designRuntimeWorkspaceCreate: 'design-runtime:workspace-create',
  designRuntimeWorkspaceOpen: 'design-runtime:workspace-open',
  designRuntimeWorkspaceClose: 'design-runtime:workspace-close',
  designRuntimeWorkspaceHome: 'design-runtime:workspace-home',
  designRuntimeWorkspaceInfo: 'design-runtime:workspace-info',
  designRuntimeWorkspaceStepConfiguration: 'design-runtime:workspace-step-configuration',
  designRuntimeWorkspaceRefreshConfig: 'design-runtime:workspace-refresh-config',
  designRuntimeWorkspaceResetFlow: 'design-runtime:workspace-reset-flow',
  designRuntimeFlowRun: 'design-runtime:flow-run',
  designRuntimeFlowRunStep: 'design-runtime:flow-run-step',
  chipViewerOpen: 'chip-viewer:open',
  chipViewerIsOpen: 'chip-viewer:is-open',
  eccRuntimeEngineeringSnapshot: 'ecc:runtime-engineering-snapshot',
  eccRuntimeWaitForOperation: 'ecc:runtime-wait-operation',
  eccRuntimeSnapshot: 'ecc:runtime-snapshot',
  eccRuntimeOperationProjection: 'ecc:runtime-operation-projection',
  eccRuntimeOperationLog: 'ecc:runtime-operation-log',
  productCommandExecute: 'product-command:execute',
  workspaceCreationModelGet: 'workspace-creation-model:get',
  agentStart: 'agent:start',
  agentStartSession: 'agent:start-session',
  agentSendMessage: 'agent:send-message',
  agentInterrupt: 'agent:interrupt',
  agentCodexGetStatus: 'agent:codex-get-status',
  agentCodexInstall: 'agent:codex-install',
  agentCodexLogin: 'agent:codex-login',
  agentCodexRecheck: 'agent:codex-recheck',
  agentCodexSetBinPath: 'agent:codex-set-bin-path',
  shellCreateSession: 'shell:create-session',
  shellWrite: 'shell:write',
  shellResize: 'shell:resize',
  shellKill: 'shell:kill',
  systemOpenExternal: 'system:open-external',
} as const

export const desktopApiEventChannels = {
  backendWorkspaceInvalidated: 'backend-workspace:invalidated',
  backendProjectComparisonInvalidated: 'backend-project-comparison:invalidated',
  backendProjectExecutionInvalidated: 'backend-project-execution:invalidated',
  menuAction: 'menu:action',
  windowResized: 'window:resized',
  windowMaximizedChanged: 'window:maximized-changed',
  shutdownStatusChanged: 'shutdown:status-changed',
  shutdownCleanupRequested: 'shutdown:cleanup-requested',
  resourcesProgress: 'resources:progress',
  designRuntimeEvent: 'design-runtime:event',
  eccRuntimeOperationProjectionInvalidated:
    'ecc:runtime-operation-projection-invalidated',
  agentEvent: 'agent:event',
  agentCodexProgress: 'agent:codex-progress',
  shellData: 'shell:data',
  shellExit: 'shell:exit',
} as const

export type DesktopApiIpcChannel =
  (typeof desktopApiIpcChannels)[keyof typeof desktopApiIpcChannels]

export type DesktopApiEventChannel =
  (typeof desktopApiEventChannels)[keyof typeof desktopApiEventChannels]
