export {
  desktopApiEventChannels,
  desktopApiIpcChannels,
  type DesktopApiEventChannel,
  type DesktopApiIpcChannel,
} from './constants/ipcChannels.ts'
export type {
  DesktopApi,
  DesktopDirectoryDialogOptions,
  DesktopFileDialogFilter,
  DesktopFileDialogOptions,
  DesktopSaveFileDialogOptions,
  DesktopRtlSourceDialogOptions,
  PickedRtlSources,
  DesktopProjectLogTailSubscriptionOptions,
  DesktopProjectDirectoryEntry,
  DesktopProjectTextFileTail,
  DesktopProjectTextFileUpdate,
  DesktopSettingsValue,
  ChipViewerOpenRequest,
  ChipViewerOpenResult,
  ChipViewerOpenStatus,
  PdkDetectedFiles,
  ScannedPdkDirectory,
  ScannedRtlDirectory,
  VersionInfo,
  WorkspaceDirectoryReplacement,
  WorkspaceOpenOrFocusResult,
} from './contracts/desktopApi.ts'
export type {
  EccFlowRunRequest,
  EccFlowRunResult,
  EccFlowRunStepRequest,
  EccFlowRunStepResult,
  EccLayoutEditApplyRequest,
  EccLayoutEditApplyResult,
  EccLayoutEditBeginRequest,
  EccLayoutEditBeginResult,
  EccLayoutEditDiscardRequest,
  EccLayoutEditDiscardResult,
  EccLayoutEditSaveRequest,
  EccLayoutEditSaveResult,
  EccRpcHelloResult,
  EccRpcPingResult,
  EccRpcShutdownResult,
  EccRuntimeApi,
  EccRuntimeError,
  EccRuntimeEvent,
  EccSignoffReviewDetail,
  EccSignoffReviewDetailKind,
  EccSignoffReviewGroup,
  EccSignoffReviewRisk,
  EccSignoffReviewStatus,
  EccWorkspaceCloseResult,
  EccWorkspaceCreateRequest,
  EccWorkspaceCreateResult,
  EccWorkspaceExportSignoffRequest,
  EccWorkspaceExportSignoffResult,
  EccWorkspaceHandleRequest,
  EccWorkspaceHomeResult,
  EccWorkspaceInspectSignoffResult,
  EccWorkspaceInfoRequest,
  EccWorkspaceInfoResult,
  EccWorkspaceOpenRequest,
  EccWorkspaceOpenResult,
  EccWorkspaceRefreshConfigResult,
  EccWorkspaceResetFlowResult,
  EccWorkspaceSyncConfigRequest,
  EccWorkspaceSyncConfigResult,
} from './contracts/eccRuntime.ts'
export type {
  ResourceAction,
  ResourceImportLocalRequest,
  ResourceImportPdkRequest,
  ResourceInfo,
  ResourceInstallRequest,
  ResourceJob,
  ResourceList,
  MpcSpecReadResult,
  ResourceOperationResult,
  ResourceStatus,
  ResourceType,
} from './contracts/resources.ts'
export type {
  DesktopShellDataEvent,
  DesktopShellExitEvent,
  DesktopShellSession,
  DesktopShellSessionOptions,
} from './contracts/desktopShell.ts'
export type {
  DesktopAgentEvent,
  DesktopAgentEventType,
  DesktopAgentListSessionsRequest,
  DesktopAgentListSessionsResponse,
  DesktopAgentProviderRequest,
  DesktopAgentResumeSessionRequest,
  DesktopAgentResumeSessionResponse,
  DesktopAgentSendMessageRequest,
  DesktopAgentSendMessageResponse,
  DesktopAgentSessionSummary,
  DesktopAgentSetModeRequest,
  DesktopAgentStartRequest,
  DesktopAgentStartSessionRequest,
  DesktopAgentStartSessionResponse,
  DesktopAgentStatus,
  DesktopAgentStatusState,
} from './contracts/desktopAgent.ts'
export {
  appMenuActionIds,
  desktopMenuEventIds,
  type DesktopProjectFileChangedEvent,
  type DesktopProjectFileChangeEventType,
  type DesktopProjectLogTailEvent,
  type DesktopProjectLogTailEventType,
  type AppMenuAction,
  type DesktopEventUnsubscribe,
  type DesktopMenuEventId,
} from './contracts/desktopEvents.ts'
export type { DesktopErrorCode, DesktopErrorShape } from './contracts/errors.ts'
export type {
  DesktopFailure,
  DesktopResult,
  DesktopSuccess,
  VoidDesktopResult,
} from './types/desktop.ts'
export type {
  WorkspaceConfig,
  WorkspaceParameters,
  WorkspaceStatus,
  WorkspaceSummary,
} from './types/workspace.ts'
export type {
  WorkspaceDesignFileAddResult,
  WorkspaceDesignFileEntry,
  WorkspaceDesignFileSkip,
} from './types/designFiles.ts'
export type {
  WorkspaceResourceFile,
  WorkspaceResourceIndex,
  WorkspaceResourceStatus,
  WorkspaceStepInfoRequest,
  WorkspaceStepInfoResult,
  WorkspaceStepResource,
  WorkspaceTechResources,
} from './types/workspaceResources.ts'
export {
  isAbsoluteLocalPath,
  isWindowsDrivePath,
  joinLocalPath,
  LocalPathOutsideRootError,
  normalizeLocalPath,
  resolveContainedLocalPath,
  resolveProjectFileAbsolutePath,
} from './utils/localPath.ts'
export { isHdlFilePath } from './utils/hdlPath.ts'
export { validateMpcSpec } from './utils/mpcSpec.ts'
export type { ValidatedMpcSpec, ValidatedMpcSpecDesign } from './utils/mpcSpec.ts'
export {
  applyProjectManifestMutation,
  archiveWorkspaceInManifest,
  createProjectManifestDraft,
  deleteWorkspaceFromManifest,
  ensureProjectQorBaseline,
  parseProjectManifest,
  projectManifestFlowSteps,
  recordReplacementBackupInManifest,
  registerWorkspaceInManifest,
  serializeProjectManifest,
} from './utils/projectManifest.ts'
export type {
  ProjectManifest,
  ProjectManifestBaseDesign,
  ProjectManifestDraftInput,
  ProjectManifestFlowStep,
  ProjectManifestMetricSummary,
  ProjectManifestMpc,
  ProjectManifestMpcDesign,
  ProjectManifestMutation,
  ProjectManifestMutationRequest,
  ProjectManifestMutationResult,
  ProjectManifestReplacementBackupInput,
  ProjectManifestResolvedReplacementBackupInput,
  ProjectManifestWorkspace,
  ProjectManifestWorkspaceRegistrationInput,
  ProjectManifestWorkspaceStatus,
} from './utils/projectManifest.ts'
