export {
  desktopApiEventChannels,
  desktopApiIpcChannels,
  type DesktopApiEventChannel,
  type DesktopApiIpcChannel,
} from './constants/ipcChannels.ts'
export type {
  DesignRuntimeApi,
  DesignRuntimeCancelRequest,
  DesignRuntimeCancelResult,
  DesignRuntimeEvent,
  DesignRuntimeFlowRunRequest,
  DesignRuntimeFlowRunStepRequest,
  DesignRuntimeHelloResult,
  DesignRuntimeTargetRequest,
  DesignRuntimeWorkspaceCreateRequest,
  DesignRuntimeWorkspaceHandleRequest,
  DesignRuntimeWorkspaceInfoRequest,
  DesignRuntimeWorkspaceOpenRequest,
  DesignRuntimeWorkspaceSyncConfigRequest,
} from './contracts/designRuntime.ts'
export type {
  DesktopApi,
  DesktopDirectoryDialogOptions,
  DesktopFileDialogFilter,
  DesktopFileDialogOptions,
  DesktopSaveFileDialogOptions,
  DesktopRtlSourceDialogOptions,
  PickedRtlSources,
  DesktopProjectLogTailSubscriptionOptions,
  DesktopProjectDirectoryEntry,
  DesktopProjectManagementWorkspaceTextsRequest,
  DesktopProjectManagementWorkspaceTextsResult,
  DesktopProjectTextFileChunk,
  DesktopProjectTextFileTail,
  DesktopProjectTextFileUpdate,
  DesktopSettingsValue,
  ChipViewerOpenRequest,
  ChipViewerOpenResult,
  ChipViewerOpenStatus,
  PdkDetectedFiles,
  ScannedPdkDirectory,
  ScannedRtlDirectory,
  VersionInfo,
  WorkspaceDirectoryReplacement,
  WorkspaceOpenOrFocusResult,
} from './contracts/desktopApi.ts'
export type {
  EccFlowRunRequest,
  EccFlowRunResult,
  EccFlowRunStepRequest,
  EccFlowRunStepResult,
  EccLayoutEditApplyRequest,
  EccLayoutEditApplyResult,
  EccLayoutEditBeginRequest,
  EccLayoutEditBeginResult,
  EccLayoutEditDiscardRequest,
  EccLayoutEditDiscardResult,
  EccLayoutEditSaveRequest,
  EccLayoutEditSaveResult,
  EccRpcHelloResult,
  EccRpcPingResult,
  EccRpcShutdownResult,
  EccRuntimeApi,
  EccRuntimeError,
  EccRuntimeEvent,
  EccRuntimeInterruptibility,
  EccRuntimeOperation,
  EccRuntimeOperationKind,
  EccRuntimeOperationRequest,
  EccRuntimeOperationState,
  EccRuntimeProtocolEvent,
  EccRuntimeProtocolPayload,
  EccRuntimeStartFlowRequest,
  EccRuntimeStartStepRequest,
  EccRuntimeStepRenderedAckRequest,
  EccRuntimeStepSnapshot,
  EccSignoffReviewDetail,
  EccSignoffReviewDetailKind,
  EccSignoffReviewGroup,
  EccSignoffReviewRisk,
  EccSignoffReviewStatus,
  EccWorkspaceCloseResult,
  EccWorkspaceCreateRequest,
  EccWorkspaceCreateResult,
  EccWorkspaceExportSignoffRequest,
  EccWorkspaceExportSignoffResult,
  SignoffAdditionalFile,
  EccWorkspaceHandleRequest,
  EccWorkspaceHomeResult,
  EccWorkspaceInspectSignoffResult,
  EccWorkspaceInfoRequest,
  EccWorkspaceInfoResult,
  EccWorkspaceOpenRequest,
  EccWorkspaceOpenResult,
  EccWorkspaceRefreshConfigResult,
  EccWorkspaceResetFlowResult,
  EccWorkspaceSyncConfigRequest,
  EccWorkspaceSyncConfigResult,
  EccWorkspaceRuntimeSnapshot,
} from './contracts/eccRuntime.ts'
export type {
  ResourceAction,
  ResourceImportLocalRequest,
  ResourceImportPdkRequest,
  ResourceInfo,
  ResourceInstallRequest,
  ResourceJob,
  ResourceList,
  MpcSpecReadResult,
  ResourceOperationResult,
  ResourceStatus,
  ResourceType,
  ResourceUpdateCheckItem,
  ResourceUpdateCheckResult,
} from './contracts/resources.ts'
export type {
  DesktopShellDataEvent,
  DesktopShellExitEvent,
  DesktopShellSession,
  DesktopShellSessionOptions,
} from './contracts/desktopShell.ts'
export type {
  DesktopCodexAuthState,
  DesktopCodexDependencyState,
  DesktopCodexDependencyStatus,
  DesktopCodexInstallProgressEvent,
  DesktopCodexSetBinPathRequest,
} from './contracts/desktopCodex.ts'
export { DESKTOP_CODEX_BIN_SETTING_KEY } from './contracts/desktopCodex.ts'
export type {
  DesktopAgentEvent,
  DesktopAgentChoice,
  DesktopAgentChoiceOption,
  DesktopAgentContractField,
  DesktopAgentExecutionContract,
  DesktopAgentParameterWriteFile,
  DesktopAgentParameterWriteSurface,
  DesktopAgentWorkspaceContinueContract,
  DesktopAgentWorkspaceParameterUpdateContract,
  DesktopAgentWorkspaceParameterWrite,
  DesktopAgentWorkspaceRerunContract,
  DesktopAgentWorkspaceRerunExecuteRequest,
  DesktopAgentWorkspaceRerunParameterPatch,
  DesktopAgentWorkspaceRerunParameterValue,
  DesktopAgentWorkspaceRerunPrepareRequest,
  DesktopAgentWorkspaceRerunPrepareResult,
  DesktopAgentWorkspaceSetupContract,
  DesktopAgentWorkspaceSetupParameters,
  DesktopAgentEventType,
  DesktopAgentInterruptRequest,
  DesktopAgentListSessionsRequest,
  DesktopAgentListSessionsResponse,
  DesktopAgentProviderRequest,
  DesktopAgentRunStatus,
  DesktopAgentResumeSessionRequest,
  DesktopAgentResumeSessionResponse,
  DesktopAgentSendMessageRequest,
  DesktopAgentSendMessageResponse,
  DesktopAgentSessionSummary,
  DesktopAgentSetModeRequest,
  DesktopAgentStartRequest,
  DesktopAgentKnownProject,
  DesktopAgentSessionMode,
  DesktopAgentStartSessionRequest,
  DesktopAgentStartSessionResponse,
  DesktopAgentStatus,
  DesktopAgentStatusState,
} from './contracts/desktopAgent.ts'
export { desktopAgentParameterWriteFiles } from './contracts/desktopAgent.ts'
export {
  appMenuActionIds,
  desktopMenuEventIds,
  type DesktopProjectFileChangedEvent,
  type DesktopProjectFileChangeEventType,
  type DesktopProjectLogTailEvent,
  type DesktopProjectLogTailEventType,
  type AppMenuAction,
  type DesktopEventUnsubscribe,
  type DesktopMenuEventId,
} from './contracts/desktopEvents.ts'
export type { DesktopErrorCode, DesktopErrorShape } from './contracts/errors.ts'
export type {
  ManualPdkConfiguration,
  PdkBinding,
  PdkBindRequest,
  PdkImportRequest,
  PdkInstallationRecord,
  PdkInstallationSnapshot,
  PdkLocateRequest,
  PdkOwnership,
  PdkProjectRequest,
  PdkReadiness,
  PdkRequirement,
  PdkResolveBindingRequest,
  PdkWorkspaceValidationRequest,
} from './contracts/pdkInventory.ts'
export type {
  DesktopFailure,
  DesktopResult,
  DesktopSuccess,
  VoidDesktopResult,
} from './types/desktop.ts'
export type {
  DesignTool,
  WorkspaceConfig,
  WorkspaceParameters,
  WorkspaceStatus,
  WorkspaceSummary,
} from './types/workspace.ts'
export type {
  WorkspaceDesignFileAddResult,
  WorkspaceDesignFileEntry,
  WorkspaceDesignFileSkip,
} from './types/designFiles.ts'
export type {
  WorkspaceResourceFile,
  WorkspaceResourceIndex,
  WorkspaceResourceStatus,
  WorkspaceStepInfoRequest,
  WorkspaceStepInfoResult,
  WorkspaceStepResource,
  WorkspaceTechResources,
} from './types/workspaceResources.ts'
export {
  isAbsoluteLocalPath,
  isWindowsDrivePath,
  joinLocalPath,
  LocalPathOutsideRootError,
  normalizeLocalPath,
  resolveContainedLocalPath,
  resolveProjectFileAbsolutePath,
} from './utils/localPath.ts'
export { isHdlFilePath } from './utils/hdlPath.ts'
export { normalizeParameterKey, normalizeParameterKeys } from './utils/parameterKeys.ts'
export {
  projectManagementStaTimingIssuesPath,
  projectManagementWorkspaceReadablePaths,
  projectManagementWorkspaceStepAnalysisSpecs,
  projectManagementWorkspaceStepConfigPaths,
  projectManagementWorkspaceSummaryPaths,
} from './utils/projectManagementSummary.ts'
export { validateMpcSpec } from './utils/mpcSpec.ts'
export type { ValidatedMpcSpec, ValidatedMpcSpecDesign } from './utils/mpcSpec.ts'
export {
  applyProjectManifestMutation,
  archiveWorkspaceInManifest,
  createProjectManifestDraft,
  deleteWorkspaceFromManifest,
  ensureProjectQorBaseline,
  parseProjectManifest,
  projectIdFromName,
  projectManifestFlowSteps,
  recordReplacementBackupInManifest,
  registerWorkspaceInManifest,
  serializeProjectManifest,
  synchronizeProjectBaseline,
} from './utils/projectManifest.ts'
export type {
  ProjectManifest,
  ProjectManifestBaseDesign,
  ProjectManifestBaselineSyncInput,
  ProjectManifestDraftInput,
  ProjectManifestFlowStep,
  ProjectManifestMetricSummary,
  ProjectManifestMpc,
  ProjectManifestMpcDesign,
  ProjectManifestMutation,
  ProjectManifestMutationRequest,
  ProjectManifestMutationResult,
  ProjectManifestReplacementBackupInput,
  ProjectManifestResolvedReplacementBackupInput,
  ProjectManifestWorkspace,
  ProjectManifestWorkspaceRegistrationInput,
  ProjectManifestWorkspaceStatus,
} from './utils/projectManifest.ts'
export type {
  ClockMetrics,
  CongestionMetrics,
  CornerTimingRecord,
  DesignInfo,
  DesignReportData,
  DesignReportExportOptions,
  DesignReportFormat,
  DesignReportWarning,
  EvidenceProvenanceRecord,
  ExecutionMetrics,
  PhysicalMetrics,
  PowerMetrics,
  RoutingMetrics,
  StageExecutionRecord,
  TimingMetrics,
  VerificationMetrics,
} from './contracts/designReport.ts'
export {
  canonicalizeStageName,
  extractDesignReportData,
  formatDuration,
  parsePowerRpt,
  parseQorSummaryRpt,
  parseRuntimeSeconds,
  type ExtractDesignReportInput,
  type ParsedPowerMetrics,
  type ParsedQorSummaryMetrics,
} from './utils/designReportExtract.ts'
export {
  formatCsvReport,
  formatLatexReport,
  formatMarkdownReport,
  formatTextReport,
  formatTypstReport,
  generateDesignReport,
} from './utils/designReportFormatters/index.ts'
