import { describe, expect, it } from 'vitest'
import { parseMacroLocationTcl } from './chipViewerMacroLocationTcl'

describe('parseMacroLocationTcl', () => {
  it('parses the ECC saveMacroTCL handoff into macro.placements entries', () => {
    const text = [
      '# Hard-macro placement commands generated by saveMacroTCL().',
      'placeInstance u_ram0 10.000000 20.500000 R0',
      'setInstancePlacementStatus -status fixed -name u_ram0',
      'placeInstance u_ram1 150 0 MY90',
      'setInstancePlacementStatus -status fixed -name u_ram1',
      '',
    ].join('\n')

    expect(parseMacroLocationTcl(text)).toEqual([
      { instance: 'u_ram0', orientation: 'R0', x: 10, y: 20.5 },
      { instance: 'u_ram1', orientation: 'MY90', x: 150, y: 0 },
    ])
  })

  it('returns an empty list for the seeded template', () => {
    expect(parseMacroLocationTcl('# Auto-generated macro location file\n\n')).toEqual([])
  })

  it('rejects malformed statements instead of recording a partial writeback', () => {
    expect(() => parseMacroLocationTcl('placeInstance u0 1 2\n')).toThrow(
      'unsupported statement',
    )
    expect(() => parseMacroLocationTcl('placeInstance u0 1 nan R0\n')).toThrow(
      'non-finite coordinates',
    )
    expect(() => parseMacroLocationTcl('placeInstance u0 1 2 NORTH\n')).toThrow(
      'unknown orientation',
    )
    expect(() => parseMacroLocationTcl('moveInstance u0 1 2 R0\n')).toThrow(
      'unsupported statement',
    )
  })
})
