import { spawn } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { existsSync, lstatSync, readFileSync, realpathSync } from 'node:fs'
import { chmod, mkdir, rename, rm, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import {
  ECC_BUNDLE_RESOURCE_ID,
  EXPECTED_ECC_BUNDLE_VERSION,
  type CliInstallState,
  type CliInstallerProgressEvent,
  type ResourceJob,
} from '@ecos-studio/shared'
import { electronLogger } from './logger'
import {
  buildShimScript,
  resolveContainedSymlinkDir,
  executableNameFor,
  readInstallRecord,
  type CliBundleInstallRecord,
} from './cliInstallerArtifacts'
import {
  acquireAndActivateBundle,
  cleanupTempInstalls,
  sha256File,
} from './cliInstallerAcquisition'
import { type CliSpawnLike } from './cliSelfCheck'
import { CliInstallerEnvWriter } from './cliInstallerEnv'
import {
  resolveDataHome,
  resolveEccRuntimeBinDir,
  type EccRuntimeEnvOptions,
} from './eccRpc/runtimeEnv'

export type { CliSpawnLike, CliSelfCheckChild } from './cliSelfCheck'
export type { CliBundleInstallRecord } from './cliInstallerArtifacts'

interface EnsureBundleOptions {
  onProgress?: (event: CliInstallerProgressEvent) => void
  /**
   * Also (re)install the `ecos-ecc` shim as part of this install. Used for
   * user-initiated installs and first-use setup; background drift refreshes
   * deliberately leave the shim untouched.
   */
  installShim?: boolean
}

/** The subset of ResourceManagerService the installer consumes. */
export interface CliInstallerResourceManager {
  downloadRegistryAssetToDirectory(request: {
    resourceId: string
    version: string
    destinationDir: string
    listener?: (event: ResourceJob) => void
    signal?: AbortSignal
  }): Promise<{ version: string; sha256: string; size: number | null }>
  resolveRegistryToolAsset(
    resourceId: string,
    version?: string,
  ): Promise<{ version: string; sha256: string; size: number | null }>
  createRuntimeEnv(
    baseEnv: NodeJS.ProcessEnv,
    options: { platform: NodeJS.Platform },
  ): Promise<NodeJS.ProcessEnv>
  onManifestChanged(listener: () => void | Promise<void>): () => void
}

export interface CliInstallerServiceOptions {
  resourceManager: CliInstallerResourceManager
  env?: NodeJS.ProcessEnv
  platform?: NodeJS.Platform
  isPackaged?: boolean
  appPath?: string
  resourcesPath?: string
  userDataPath?: string
  dataHome?: string
  /** Bundle home root; defaults to `<dataHome>/ecos-studio/ecc-runtime`. */
  dataDir?: string
  /** Directory receiving the `ecos-ecc` shim; defaults to `~/.local/bin`. */
  binDir?: string
  homeDir?: () => string
  spawn?: CliSpawnLike
  expectedVersion?: string
  selfCheckTimeoutMs?: number
  now?: () => Date
}

const SHIM_NAME = 'ecos-ecc'
const SHIM_MARKER = '# Generated by ECOS Studio'
const SELF_CHECK_TIMEOUT_MS = 30_000
const ENV_REGENERATION_DEBOUNCE_MS = 500

export class CliInstallerService {
  private readonly resourceManager: CliInstallerResourceManager
  private readonly env: NodeJS.ProcessEnv
  private readonly platform: NodeJS.Platform
  private readonly isPackaged: boolean
  private readonly appPath: string
  private readonly resourcesPath: string | null
  private readonly userDataPath: string
  private readonly dataHome: string
  private readonly explicitDataHome: string | undefined
  private readonly dataDir: string
  private readonly binDir: string
  private readonly resolveHomeDir: () => string
  private readonly spawnImpl: CliSpawnLike
  private readonly expectedVersion: string
  private readonly selfCheckTimeoutMs: number
  private readonly resolveNow: () => Date

  private ensurePromise: Promise<string> | null = null
  private uninstalling = false
  private lastFailure: string | null = null
  private lastShimFailure: string | null = null
  private readonly progressListeners = new Set<
    (event: CliInstallerProgressEvent) => void
  >()
  private lastProgress: CliInstallerProgressEvent | null = null
  private readonly unsubscribeManifest: () => void
  private readonly envWriter: CliInstallerEnvWriter
  private envRegenerationTimer: NodeJS.Timeout | null = null

  constructor(options: CliInstallerServiceOptions) {
    this.resourceManager = options.resourceManager
    this.env = options.env ?? process.env
    this.platform = options.platform ?? process.platform
    this.isPackaged = options.isPackaged ?? false
    this.appPath = options.appPath ?? process.cwd()
    this.resourcesPath =
      options.resourcesPath ??
      (this.isPackaged ? (this.env.ECOS_ELECTRON_RESOURCES_PATH ?? null) : null)
    this.userDataPath = options.userDataPath ?? join(this.env.HOME ?? '', '.config')
    this.explicitDataHome = options.dataHome
    this.dataHome = options.dataHome ?? resolveDataHome(this.eccRuntimeOptions())
    this.resolveHomeDir = options.homeDir ?? homedir
    this.dataDir = options.dataDir ?? join(this.dataHome, 'ecos-studio', 'ecc-runtime')
    this.binDir = options.binDir ?? join(this.resolveHomeDir(), '.local', 'bin')
    this.spawnImpl = options.spawn ?? (spawn as unknown as CliSpawnLike)
    this.expectedVersion = options.expectedVersion ?? EXPECTED_ECC_BUNDLE_VERSION
    this.selfCheckTimeoutMs = options.selfCheckTimeoutMs ?? SELF_CHECK_TIMEOUT_MS
    this.resolveNow = options.now ?? (() => new Date())
    this.envWriter = new CliInstallerEnvWriter({
      resourceManager: options.resourceManager,
      platform: this.platform,
      eccRuntimeOptions: () => this.eccRuntimeOptions(),
    })
    this.unsubscribeManifest = options.resourceManager.onManifestChanged(() => {
      this.scheduleEnvRegeneration()
    })
  }

  dispose(): void {
    this.unsubscribeManifest()
    if (this.envRegenerationTimer) {
      clearTimeout(this.envRegenerationTimer)
      this.envRegenerationTimer = null
    }
  }

  onProgress(listener: (event: CliInstallerProgressEvent) => void): () => void {
    this.progressListeners.add(listener)
    if (this.lastProgress) listener(this.lastProgress)
    return () => {
      this.progressListeners.delete(listener)
    }
  }

  async status(): Promise<CliInstallState> {
    const base = {
      expectedVersion: this.expectedVersion,
      installedVersion: null,
      source: null,
      versionDir: null,
      shimPath: null,
      selfCheck: null,
      error: null,
    }
    if (this.platform !== 'linux') {
      return {
        ...base,
        status: 'unsupported',
        error:
          'The ecos-ecc CLI installer currently supports Linux only; ECC does not run on this platform yet.',
      }
    }
    if (this.ensurePromise) {
      return { ...base, status: 'installing' }
    }
    if (!this.isPackaged) {
      const shimPath = join(this.binDir, SHIM_NAME)
      return {
        ...base,
        status: 'dev-wrapper',
        versionDir: existsSync(this.dataDir) ? this.dataDir : null,
        shimPath: this.ownsShim(shimPath) ? shimPath : null,
        error: null,
      }
    }
    const install = await this.readActiveInstall()
    if (!install) {
      // lstat: existsSync is false for a dangling link, which must still be
      // reported (and repaired) rather than silently reading as absent.
      if (this.currentLinkExists()) {
        const versionDir = await this.resolveCurrentVersionDir()
        let problem = "the 'current' link is dangling"
        if (versionDir) {
          const loaded = await readInstallRecord(versionDir, this.platform)
          if ('error' in loaded) problem = loaded.error
        }
        return {
          ...base,
          status: 'failed',
          error: `The active ECC install is incomplete (${problem}); reinstall to repair it.`,
        }
      }
      return {
        ...base,
        status: this.lastFailure ? 'failed' : 'not-installed',
        error: this.lastFailure,
      }
    }
    const shimPath = this.installedShimPath()
    if (!shimPath) {
      // Without the shim the host command does not exist, so this is not a
      // ready install even though the bundle itself is intact. Surface the
      // recorded shim failure (with manual remediation) when present.
      return {
        expectedVersion: this.expectedVersion,
        installedVersion: install.version,
        source: install.source,
        versionDir: this.currentLinkPath(),
        shimPath: null,
        selfCheck: install.selfCheck,
        status: 'failed',
        error:
          this.lastShimFailure ??
          'The ECC bundle is installed but the ecos-ecc shim is missing; reinstall to recreate it.',
      }
    }
    return {
      expectedVersion: this.expectedVersion,
      installedVersion: install.version,
      source: install.source,
      versionDir: this.currentLinkPath(),
      shimPath,
      selfCheck: install.selfCheck,
      status: install.selfCheck.ok ? 'ready' : 'self-check-failed',
      error: install.selfCheck.ok
        ? null
        : (install.selfCheck.detail ??
          'The ECC bundle self-check failed; see the remediation hints in the logs.'),
    }
  }

  /**
   * Install (or refresh) the ECC bundle into the bundle home. Bundled
   * packages copy their embedded binaries; slim packages download the pinned
   * registry asset. The `ecos-ecc` shim is deliberately NOT touched here so
   * background drift refreshes never rewrite it; call installShim()
   * explicitly for user-initiated installs and first-use setup.
   */
  async ensureBundle(options: EnsureBundleOptions = {}): Promise<string> {
    if (this.platform !== 'linux') {
      throw new Error('The ECC bundle installer currently supports Linux only')
    }
    if (!this.isPackaged) {
      throw new Error(
        'Development mode runs the repository wrapper directly; there is no bundle to install',
      )
    }
    if (this.uninstalling) {
      throw new Error('An uninstall is in progress; retry the install afterwards')
    }
    if (this.ensurePromise) {
      // Another install owns the pipeline. A requested shim install is
      // chained INTO the tracked transaction (not run outside it), so
      // uninstall guards still apply and failures publish terminal error
      // progress with the manual-shim remediation.
      const pending = this.ensurePromise
      if (!options.installShim) {
        return await pending
      }
      this.ensurePromise = (async () => {
        const versionDir = await pending
        try {
          await this.installShim()
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error)
          this.lastShimFailure = message
          this.publishProgress(options, {
            phase: 'error',
            progress: 0,
            message,
            error: message,
          })
          throw error
        }
        this.lastShimFailure = null
        this.publishProgress(options, {
          phase: 'done',
          progress: 1,
          message: 'ECC bundle installed successfully',
        })
        return versionDir
      })()
        .catch((error: unknown) => {
          this.lastFailure = error instanceof Error ? error.message : String(error)
          throw error
        })
        .finally(() => {
          this.ensurePromise = null
        })
      return await this.ensurePromise
    }
    this.ensurePromise = this.runEnsureBundle(options)
      .catch((error: unknown) => {
        const message = error instanceof Error ? error.message : String(error)
        this.lastFailure = message
        this.publishProgress(options, {
          phase: 'error',
          progress: 0,
          message,
          error: message,
        })
        throw error
      })
      .finally(() => {
        this.ensurePromise = null
      })
    return await this.ensurePromise
  }

  /** Write the `ecos-ecc` shim into the host bin directory. */
  async installShim(): Promise<void> {
    if (this.platform !== 'linux') {
      throw new Error('The ecos-ecc shim currently supports Linux only')
    }
    if (!this.isPackaged) {
      // Ensure the repository wrapper shim (runtime-bin/ecc) and the shared
      // env file exist before the shim references them.
      const runtimeBinDir = resolveEccRuntimeBinDir(this.eccRuntimeOptions())
      if (!runtimeBinDir) {
        throw new Error(
          'Development mode requires a repository checkout with ecos/scripts/ecc-wrapper.sh',
        )
      }
      await this.regenerateEnvFile()
    }
    const shimPath = join(this.binDir, SHIM_NAME)
    // lstat, not existsSync: a dangling symlink is still an existing entry
    // that must not be silently replaced.
    if (this.entryExists(shimPath) && !this.ownsShim(shimPath)) {
      // Never clobber a command we did not generate.
      throw new Error(
        `Refusing to overwrite ${shimPath}: it exists and was not generated by ECOS Studio. Remove it manually, then reinstall.`,
      )
    }
    const content = this.shimContent()
    try {
      await mkdir(this.binDir, { recursive: true })
      // Write to a unique temp file, chmod explicitly (writeFile's mode only
      // applies on creation), and rename atomically so a partial write can
      // never damage a previously working shim.
      const tempShimPath = join(
        this.binDir,
        `.${SHIM_NAME}.tmp-${randomUUID().slice(0, 8)}`,
      )
      await writeFile(tempShimPath, content)
      try {
        await chmod(tempShimPath, 0o755)
        await rename(tempShimPath, shimPath)
      } catch (error) {
        await rm(tempShimPath, { force: true }).catch(() => undefined)
        throw error
      }
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error)
      throw new Error(
        `Unable to write ${shimPath} (${reason}). Create the shim manually with:\n${content}`,
      )
    }
    electronLogger.info('[cli-installer] Installed shim %s', shimPath)
    this.lastShimFailure = null
  }

  async uninstall(): Promise<void> {
    if (this.platform !== 'linux') {
      throw new Error('The ECC bundle installer currently supports Linux only')
    }
    if (this.ensurePromise) {
      throw new Error(
        'An install is in progress; wait for it to finish before uninstalling',
      )
    }
    this.uninstalling = true
    try {
      const shimPath = join(this.binDir, SHIM_NAME)
      // Only remove the shim when we generated it; a foreign command at that
      // path belongs to the user.
      if (this.ownsShim(shimPath)) {
        await rm(shimPath, { force: true })
      }
      if (this.isPackaged) {
        await rm(this.dataDir, { force: true, recursive: true })
      } else {
        await rm(join(this.dataDir, 'env'), { force: true })
      }
      this.lastFailure = null
    } finally {
      this.uninstalling = false
    }
  }

  /**
   * Startup maintenance: discard leftover staging directories, then compare
   * the active install against the identity of the source the running
   * package provides and reinstall in the background on drift. Registry
   * lookup failures keep the current install untouched.
   */
  async checkSyncOnStartup(): Promise<void> {
    if (this.platform !== 'linux' || !this.isPackaged) return
    await cleanupTempInstalls(this.dataDir)
    const install = await this.readActiveInstall()
    if (!install) {
      if (this.currentLinkExists()) {
        await this.reinstallOnDrift('active install is incomplete or unreadable')
      }
      return
    }
    if (install.version !== this.expectedVersion) {
      await this.reinstallOnDrift(`version ${install.version} != ${this.expectedVersion}`)
      return
    }
    // Compare against the identity of the source the running package
    // actually provides, so slim<->fat upgrades re-acquire from the source
    // the GUI resolution prefers.
    try {
      const packagedDir = this.resolvePackagedBinariesDir()
      if (packagedDir) {
        const hash = await sha256File(join(packagedDir, executableNameFor(this.platform)))
        if (install.source !== 'bundled' || install.sha256 !== hash) {
          await this.reinstallOnDrift(
            'the embedded bundle differs from the active install',
          )
        }
        return
      }
      const asset = await this.resourceManager.resolveRegistryToolAsset(
        ECC_BUNDLE_RESOURCE_ID,
        this.expectedVersion,
      )
      if (install.source !== 'downloaded' || install.sha256 !== asset.sha256) {
        await this.reinstallOnDrift('the registry bundle differs from the active install')
      }
    } catch (error) {
      electronLogger.info(
        '[cli-installer] Skipping drift check: %s',
        error instanceof Error ? error.message : String(error),
      )
    }
  }

  /** Regenerate the shared env file from the current runtime env. */
  async regenerateEnvFile(): Promise<void> {
    if (this.platform !== 'linux') return
    if (this.isPackaged) {
      const versionDir = await this.resolveCurrentVersionDir()
      if (!versionDir) return
      await this.writeEnvFile(versionDir, join(versionDir, 'binaries'))
      return
    }
    await mkdir(this.dataDir, { recursive: true })
    await this.writeEnvFile(
      this.dataDir,
      resolveEccRuntimeBinDir(this.eccRuntimeOptions()),
    )
  }

  private async runEnsureBundle(options: EnsureBundleOptions): Promise<string> {
    this.lastFailure = null
    const versionDir = await acquireAndActivateBundle({
      dataDir: this.dataDir,
      platform: this.platform,
      expectedVersion: this.expectedVersion,
      resolvePackagedBinariesDir: () => this.resolvePackagedBinariesDir(),
      resourceManager: this.resourceManager,
      buildRuntimeEnv: (binariesDirOverride) =>
        this.envWriter.buildRuntimeEnv(binariesDirOverride),
      writeEnvFile: (targetDir, eccBinDir, libDirProbe) =>
        this.writeEnvFile(targetDir, eccBinDir, libDirProbe),
      spawnImpl: this.spawnImpl,
      selfCheckTimeoutMs: this.selfCheckTimeoutMs,
      now: this.resolveNow,
      publish: (event) => this.publishProgress(options, event),
    })
    // The terminal 'done' event is published only after the shim is in place
    // (when requested), so a completed install always means a usable CLI.
    if (options.installShim) {
      try {
        await this.installShim()
      } catch (error) {
        this.lastShimFailure = error instanceof Error ? error.message : String(error)
        throw error
      }
    }
    this.publishProgress(options, {
      phase: 'done',
      progress: 1,
      message: 'ECC bundle installed successfully',
    })
    electronLogger.info('[cli-installer] Installed ECC bundle at %s', versionDir)
    return versionDir
  }

  private async reinstallOnDrift(reason: string): Promise<void> {
    electronLogger.info(
      '[cli-installer] ECC bundle drift detected (%s); reinstalling',
      reason,
    )
    try {
      await this.ensureBundle()
    } catch (error) {
      electronLogger.warn(
        '[cli-installer] Background reinstall failed: %s',
        error instanceof Error ? error.message : String(error),
      )
    }
  }

  /** True when the file at `shimPath` is a shim we generated. */
  private ownsShim(shimPath: string): boolean {
    try {
      return readFileSync(shimPath, 'utf8').includes(SHIM_MARKER)
    } catch {
      return false
    }
  }

  /** lstat-based existence: true for dangling symlinks too. */
  private entryExists(entryPath: string): boolean {
    try {
      lstatSync(entryPath)
      return true
    } catch {
      return false
    }
  }

  /** Path of our installed shim, or null when it is absent or foreign. */
  private installedShimPath(): string | null {
    const shimPath = join(this.binDir, SHIM_NAME)
    return this.ownsShim(shimPath) ? shimPath : null
  }

  private async readActiveInstall(): Promise<CliBundleInstallRecord | null> {
    const versionDir = await this.resolveCurrentVersionDir()
    if (!versionDir) return null
    // Only a complete install counts as active; damaged directories are
    // re-acquired by the drift check. A passing recorded self-check is not
    // required here so status() can surface self-check failures.
    const loaded = await readInstallRecord(versionDir, this.platform)
    return 'record' in loaded ? loaded.record : null
  }

  private async resolveCurrentVersionDir(): Promise<string | null> {
    const linkPath = join(this.dataDir, 'current')
    // Physical containment check: a purely lexical check on the readlink
    // target is bypassable with intermediate symlinks.
    return resolveContainedSymlinkDir(linkPath, this.dataDir)
  }

  /**
   * Whether the `current` symlink exists at all — including dangling links,
   * which existsSync reports as absent.
   */
  private currentLinkExists(): boolean {
    try {
      lstatSync(join(this.dataDir, 'current'))
      return true
    } catch {
      return false
    }
  }

  private currentLinkPath(): string {
    const linkPath = join(this.dataDir, 'current')
    try {
      return realpathSync(linkPath)
    } catch {
      return linkPath
    }
  }

  private resolvePackagedBinariesDir(): string | null {
    if (!this.resourcesPath) return null
    const binariesDir = join(this.resourcesPath, 'binaries')
    return existsSync(join(binariesDir, executableNameFor(this.platform)))
      ? binariesDir
      : null
  }

  private eccRuntimeOptions(): EccRuntimeEnvOptions {
    const baseEnv: NodeJS.ProcessEnv = { ...this.env }
    if (this.isPackaged && this.resourcesPath) {
      baseEnv.ECOS_ELECTRON_RESOURCES_PATH = this.resourcesPath
    }
    return {
      appPath: this.appPath,
      cwd: process.cwd(),
      env: baseEnv,
      isPackaged: this.isPackaged,
      platform: this.platform,
      userDataPath: this.userDataPath,
      ...(this.explicitDataHome !== undefined ? { dataHome: this.explicitDataHome } : {}),
    }
  }

  private async writeEnvFile(
    targetDir: string,
    eccBinDir: string | null,
    libDirProbe?: string,
  ): Promise<void> {
    await this.envWriter.writeEnvFile(targetDir, eccBinDir, libDirProbe)
  }

  private shimContent(): string {
    return buildShimScript({
      isPackaged: this.isPackaged,
      dataDir: this.dataDir,
      devWrapper: join(this.userDataPath, 'runtime-bin', 'ecc'),
    })
  }

  private publishProgress(
    options: EnsureBundleOptions,
    event: {
      phase: string
      progress: number
      message: string
      error?: string | null
    },
  ): void {
    const payload: CliInstallerProgressEvent = {
      id: randomUUID(),
      resource_id: ECC_BUNDLE_RESOURCE_ID,
      action: 'install',
      phase: event.phase,
      progress: event.progress,
      message: event.message,
      error: event.error ?? null,
    }
    this.lastProgress = payload
    options.onProgress?.(payload)
    for (const listener of this.progressListeners) {
      try {
        listener(payload)
      } catch (error) {
        electronLogger.warn(
          '[cli-installer] Progress listener failed: %s',
          error instanceof Error ? error.message : String(error),
        )
      }
    }
  }

  private scheduleEnvRegeneration(): void {
    if (this.platform !== 'linux') return
    if (this.envRegenerationTimer) clearTimeout(this.envRegenerationTimer)
    this.envRegenerationTimer = setTimeout(() => {
      this.envRegenerationTimer = null
      void this.regenerateEnvFile().catch((error: unknown) => {
        electronLogger.warn(
          '[cli-installer] Env file regeneration failed: %s',
          error instanceof Error ? error.message : String(error),
        )
      })
    }, ENV_REGENERATION_DEBOUNCE_MS)
  }
}
