import {
  constants as fsConstants,
  existsSync,
  lstatSync,
  realpathSync,
  statSync,
} from 'node:fs'
import { access, readFile } from 'node:fs/promises'
import { isAbsolute, join, relative } from 'node:path'
import type { CliInstallSelfCheck, CliInstallSource } from '@ecos-studio/shared'

/**
 * Pure shell/env-file artifact generation for the ECC bundle installer:
 * POSIX quoting, the env-file allowlist, the generated env file content,
 * the ecos-ecc shim script, and the install receipt shape.
 */

export interface CliBundleInstallRecord {
  version: string
  sha256: string
  source: CliInstallSource
  installedAt: string
  selfCheck: CliInstallSelfCheck
}

/** POSIX single-quote a value so it stays literal inside sourced scripts. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

export function pathSeparator(platform: NodeJS.Platform): string {
  return platform === 'win32' ? ';' : ':'
}

export function executableNameFor(platform: NodeJS.Platform): string {
  return platform === 'win32' ? 'ecc.cmd' : 'ecc'
}

/**
 * Finite allowlist of ECC runtime variables for the generated env file.
 * Session-specific variables (HOME, USER, DISPLAY, XDG_*, SHELL, ...) are
 * inherited from the invoking terminal instead; ECOS_ELECTRON_* variables
 * describe the GUI process (e.g. ephemeral AppImage mounts) and are excluded.
 */
export const ECC_RUNTIME_ENV_KEYS = new Set([
  'CHIPCOMPILER_OSS_CAD_DIR',
  'ECOS_FE_CLI',
  'ECOS_FE_COMPILER_ROOT',
  'ECOS_FE_RESOURCE_ROOTS',
  'ECOS_FE_SOC_ROOT',
  'ECOS_SLANG',
  'ECOS_SURFER_ASSETS_PATH',
  'ECOS_VERILATOR',
  'RISCV',
  'RISCV_PREFIX',
  'RISCV_TOOLCHAIN',
  'VERILATOR_ROOT',
])

interface BuildEnvFileOptions {
  runtimeEnv: NodeJS.ProcessEnv
  /** Resource-manager PATH (prepend directories only). */
  toolPathValue: string
  platform: NodeJS.Platform
  /** ECC binaries directory the file must reference; null omits it. */
  eccBinDir: string | null
  /**
   * Where to probe for `_internal/ecc_tools_bin/lib` — the staged copy when
   * the final directory does not exist yet.
   */
  libDirProbe?: string
}

/**
 * Build the generated env file: ECC-relevant variables only, with PATH and
 * LD_LIBRARY_PATH written as prepend expressions so the invoking terminal's
 * own values are preserved.
 */
export function buildEnvFileContent(options: BuildEnvFileOptions): string {
  const { runtimeEnv, toolPathValue, platform, eccBinDir, libDirProbe } = options
  const separator = pathSeparator(platform)
  const toolBinDirs = toolPathValue.split(separator).filter((entry) => entry !== '')
  const pathDirs = [...toolBinDirs]
  if (eccBinDir && !pathDirs.includes(eccBinDir)) pathDirs.push(eccBinDir)

  const lines: string[] = [
    '# Generated by ECOS Studio. Regenerated on installs; do not edit.',
    // The directories are single-quoted so arbitrary paths stay literal,
    // while the caller's own value (outside the quotes) is still expanded.
    `PATH=${shellQuote(pathDirs.join(separator))}:$PATH`,
  ]
  if (eccBinDir) {
    const libDir = join(eccBinDir, '_internal', 'ecc_tools_bin', 'lib')
    if (platform === 'linux' && existsSync(libDirProbe ?? libDir)) {
      lines.push(`LD_LIBRARY_PATH=${shellQuote(libDir)}:$LD_LIBRARY_PATH`)
    }
  }
  for (const [key, value] of Object.entries(runtimeEnv)) {
    if (typeof value !== 'string' || value === '') continue
    if (key === 'PATH' || key === 'LD_LIBRARY_PATH') continue
    if (!ECC_RUNTIME_ENV_KEYS.has(key)) continue
    lines.push(`${key}=${shellQuote(value)}`)
  }
  return `${lines.join('\n')}\n`
}

export interface ShimScriptOptions {
  isPackaged: boolean
  /** Bundle home root (packaged) or shared env dir (development). */
  dataDir: string
  /** Repository runtime-bin shim (development mode only). */
  devWrapper: string
}

export function buildShimScript(options: ShimScriptOptions): string {
  if (options.isPackaged) {
    const envPath = join(options.dataDir, 'current', 'env')
    const executable = join(options.dataDir, 'current', 'binaries', 'ecc')
    return [
      '#!/bin/sh',
      '# Generated by ECOS Studio.',
      `set -a; . ${shellQuote(envPath)}; set +a`,
      `exec ${shellQuote(executable)} "$@"`,
      '',
    ].join('\n')
  }
  const envPath = join(options.dataDir, 'env')
  return [
    '#!/bin/sh',
    '# Generated by ECOS Studio (development mode: runs the repository wrapper).',
    `set -a; . ${shellQuote(envPath)}; set +a`,
    `exec ${shellQuote(options.devWrapper)} "$@"`,
    '',
  ].join('\n')
}

/**
 * Parse an install receipt. Returns the record even when the recorded
 * self-check failed (callers decide whether that counts as usable), or null
 * when the shape is invalid.
 */
export function parseInstallRecord(raw: unknown): CliBundleInstallRecord | null {
  if (!raw || typeof raw !== 'object') return null
  const record = raw as Partial<CliBundleInstallRecord>
  if (
    typeof record.version !== 'string' ||
    typeof record.sha256 !== 'string' ||
    (record.source !== 'bundled' && record.source !== 'downloaded') ||
    !record.selfCheck ||
    typeof record.selfCheck.ok !== 'boolean'
  ) {
    return null
  }
  return {
    version: record.version,
    sha256: record.sha256,
    source: record.source,
    installedAt: typeof record.installedAt === 'string' ? record.installedAt : '',
    selfCheck: {
      ok: record.selfCheck.ok,
      detail:
        typeof record.selfCheck.detail === 'string' ? record.selfCheck.detail : null,
    },
  }
}

/**
 * Load the receipt of an installed version directory and validate its
 * layout. Returns the record even when the recorded self-check failed
 * (callers decide whether that counts as usable), or an error message when
 * the directory is not a complete install.
 */
export async function readInstallRecord(
  versionDir: string,
  platform: NodeJS.Platform,
): Promise<{ record: CliBundleInstallRecord } | { error: string }> {
  const binariesDir = join(versionDir, 'binaries')
  try {
    await access(join(binariesDir, executableNameFor(platform)), fsConstants.X_OK)
  } catch {
    return { error: 'the ECC executable is missing or not executable' }
  }
  if (!existsSync(join(binariesDir, '_internal'))) {
    return { error: 'the bundle _internal directory is missing' }
  }
  if (!existsSync(join(versionDir, 'env'))) {
    return { error: 'the generated env file is missing' }
  }
  try {
    const record = parseInstallRecord(
      JSON.parse(await readFile(join(versionDir, 'install.json'), 'utf8')),
    )
    if (!record) {
      return { error: 'install.json is missing or unreadable' }
    }
    return { record }
  } catch {
    return { error: 'install.json is missing or unreadable' }
  }
}

/**
 * Physically resolve a 'current'-style symlink and verify it stays inside
 * allowedRoot (following any chain of intermediate symlinks) and points at
 * a directory. Returns the canonical path, or null when the link is absent,
 * dangling, escaping, or not a directory.
 */
export function resolveContainedSymlinkDir(
  linkPath: string,
  allowedRoot: string,
): string | null {
  try {
    lstatSync(linkPath)
    const physical = realpathSync(linkPath)
    const root = realpathSync(allowedRoot)
    const rel = relative(root, physical)
    if (rel.startsWith('..') || isAbsolute(rel)) return null
    return statSync(physical).isDirectory() ? physical : null
  } catch {
    return null
  }
}
