import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { runtimeBinPathEnvVariable, userZdotdirEnvVariable } from './eccRpc/runtimeEnv'

type StartupPlatform = NodeJS.Platform | 'linux' | 'darwin' | 'win32'

export interface ShellStartupPlan {
  args: string[]
  env: NodeJS.ProcessEnv
}

// zsh reads startup files from $ZDOTDIR. The wrapper directory takes over
// ZDOTDIR so these files run, while the user's real files are sourced from the
// directory that was in effect before the takeover: the inherited ZDOTDIR
// (passed in as ECOS_USER_ZDOTDIR, present whenever the parent environment
// defined the key, even with an empty value), a ZDOTDIR assigned inside the
// user's zshenv, or $HOME otherwise. The wrapper carries the user's ZDOTDIR
// state (set/unset, value, export attribute) through without fabricating it:
// the user's zshenv runs with exactly the native ZDOTDIR state, and their
// zshrc runs with ZDOTDIR restored to whatever their zshenv left behind.
// Startup-file lookups use unset-only expansion (${ZDOTDIR-$HOME}) because
// native zsh resolves an explicitly empty ZDOTDIR against the filesystem root,
// falling back to $HOME only when ZDOTDIR is unset. A readonly ZDOTDIR cannot
// be taken over: when the freeze happened before the wrapper ran, the wrapper
// files still execute (the frozen value points at them) and run the user's
// files without ever assigning ZDOTDIR; when the user's own zshenv freezes it,
// startup simply continues natively from the user's directory and the spawn
// environment still carries the runtime PATH. PATH merging preserves empty
// components, tolerates an unset path array, and deduplicates with the
// one-shot (u) flag so the user's tied path array keeps its native attributes.
const ZSH_ZSHENV = `# Generated by ECOS Studio. Run the user's zshenv with their native
# ZDOTDIR state, then hand control back to this wrapper so the runtime PATH
# merge in .zshrc still runs even if the user's zshenv redirected ZDOTDIR.
_ecos_wrapper_zdot="$ZDOTDIR"
_ecos_merge_terminal_path() {
  [ -n "\${ECOS_ELECTRON_RUNTIME_BIN_PATH:-}" ] || return 0
  if (( \${+path} )); then
    path=("\${(@s.:.)ECOS_ELECTRON_RUNTIME_BIN_PATH}" "\${path[@]}")
    path=("\${(@u)path}")
  else
    path=("\${(@s.:.)ECOS_ELECTRON_RUNTIME_BIN_PATH}")
  fi
}
if [[ "\${parameters[ZDOTDIR]-}" == *readonly* ]]; then
  # ZDOTDIR is frozen to this wrapper directory (e.g. by the system-wide
  # zshenv), so zsh reads startup files from here. Source the user's zshenv
  # from their native directory without ever assigning ZDOTDIR; the wrapper
  # .zshrc runs next and handles the rest. The internal marker is unexported
  # first so processes launched from the user's zshenv never inherit it.
  _ecos_user_zdot="\${ECOS_USER_ZDOTDIR-$HOME}"
  [ -n "\${ECOS_USER_ZDOTDIR+x}" ] && typeset +x ECOS_USER_ZDOTDIR
  [ -f "$_ecos_user_zdot/.zshenv" ] && . "$_ecos_user_zdot/.zshenv"
  ECOS_USER_ZDOTDIR="$_ecos_user_zdot"
  unset _ecos_user_zdot _ecos_wrapper_zdot
  if [[ ! -o rcs ]]; then
    # Startup files are disabled, so the wrapper .zshrc will not run either;
    # merge the runtime PATH here.
    _ecos_merge_terminal_path
    unfunction _ecos_merge_terminal_path
  fi
  return 0
fi
if [ -n "\${ECOS_USER_ZDOTDIR+x}" ]; then
  ZDOTDIR="$ECOS_USER_ZDOTDIR"
  typeset +x ECOS_USER_ZDOTDIR
else
  typeset +x ZDOTDIR
  unset ZDOTDIR
fi
if [ "\${ZDOTDIR-$HOME}" != "$_ecos_wrapper_zdot" ] && [ -f "\${ZDOTDIR-$HOME}/.zshenv" ]; then
  . "\${ZDOTDIR-$HOME}/.zshenv"
fi
if (( \${+ZDOTDIR} )); then
  ECOS_USER_ZDOTDIR="$ZDOTDIR"
else
  unset ECOS_USER_ZDOTDIR
fi
if [[ "\${parameters[ZDOTDIR]-}" == *readonly* ]]; then
  # The user's zshenv made ZDOTDIR readonly, so this wrapper cannot regain
  # control for .zshrc. Merge the runtime PATH before continuing natively
  # from the user's directory; a native .zshrc that resets PATH afterwards
  # still wins, matching the env-only contract of unsupported shells.
  _ecos_merge_terminal_path
  unfunction _ecos_merge_terminal_path
  unset _ecos_wrapper_zdot
  return 0
fi
if [[ ! -o rcs ]]; then
  # The user's zshenv disabled startup files, so this wrapper's .zshrc will not
  # run; merge the runtime PATH here instead. ZDOTDIR is already in its native
  # state.
  _ecos_merge_terminal_path
  unfunction _ecos_merge_terminal_path
  unset _ecos_wrapper_zdot
  return 0
fi
ZDOTDIR="$_ecos_wrapper_zdot"
unset _ecos_wrapper_zdot
`

const ZSH_ZSHRC = `# Generated by ECOS Studio. Restore the user's native ZDOTDIR state,
# run their zshrc, then restore the runtime PATH so shells that reset PATH
# during startup still see ECOS tools.
_ecos_user_zdot="\${ECOS_USER_ZDOTDIR-$HOME}"
if [[ "\${parameters[ZDOTDIR]-}" == *readonly* ]]; then
  # ZDOTDIR is frozen to this wrapper directory, so zsh read this file as the
  # user's zshrc. Run the user's real zshrc from their native directory
  # instead, without ever assigning ZDOTDIR.
  [ "$_ecos_user_zdot" != "$ZDOTDIR" ] && [ -f "$_ecos_user_zdot/.zshrc" ] && . "$_ecos_user_zdot/.zshrc"
elif [ "$_ecos_user_zdot" != "$ZDOTDIR" ]; then
  if (( \${+ECOS_USER_ZDOTDIR} )); then
    ZDOTDIR="$ECOS_USER_ZDOTDIR"
  else
    unset ZDOTDIR
  fi
  [ -f "\${ZDOTDIR-$HOME}/.zshrc" ] && . "\${ZDOTDIR-$HOME}/.zshrc"
fi
unset _ecos_user_zdot
_ecos_merge_terminal_path
unfunction _ecos_merge_terminal_path
`

const BASH_RC = `# Generated by ECOS Studio. Preserve the user's bashrc, then restore the
# runtime PATH so shells that reset PATH during startup still see ECOS tools.
# Live PATH entries missing from the runtime PATH are appended afterwards;
# empty components (current-directory entries) are preserved, while an unset
# PATH stays free of fabricated entries.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
if [ -n "\${ECOS_ELECTRON_RUNTIME_BIN_PATH:-}" ]; then
  if [ "\${PATH+x}" = x ]; then
    _ecos_path="$PATH"
    PATH="$ECOS_ELECTRON_RUNTIME_BIN_PATH"
    _ecos_parts="$_ecos_path"
    while [[ "$_ecos_parts" == *:* ]]; do
      _ecos_dir="\${_ecos_parts%%:*}"
      _ecos_parts="\${_ecos_parts#*:}"
      [[ ":$PATH:" == *":$_ecos_dir:"* ]] || PATH="$PATH:$_ecos_dir"
    done
    [[ ":$PATH:" == *":$_ecos_parts:"* ]] || PATH="$PATH:$_ecos_parts"
    unset _ecos_path _ecos_parts _ecos_dir
  else
    PATH="$ECOS_ELECTRON_RUNTIME_BIN_PATH"
  fi
  export PATH
fi
`

function writeStartupFile(filePath: string, content: string): void {
  mkdirSync(dirname(filePath), { recursive: true })
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === content) {
    return
  }
  writeFileSync(filePath, content)
}

export function ensureShellStartupFiles(startupDir: string): void {
  writeStartupFile(join(startupDir, 'zsh', '.zshenv'), ZSH_ZSHENV)
  writeStartupFile(join(startupDir, 'zsh', '.zshrc'), ZSH_ZSHRC)
  writeStartupFile(join(startupDir, 'bash', 'rc'), BASH_RC)
}

export function planShellStartup(options: {
  shell: string
  env: NodeJS.ProcessEnv
  platform: StartupPlatform
  startupDir: string
}): ShellStartupPlan {
  // The runtime env carries the ECOS-managed bin directories in
  // ECOS_ELECTRON_RUNTIME_BIN_PATH; the startup wrappers re-apply them after
  // shell startup files that reset PATH. Without the marker there is nothing
  // to re-apply, so unsupported shells and unmodified envs get a no-op plan.
  const runtimeBinPath = options.env[runtimeBinPathEnvVariable]
  if (options.platform === 'win32' || !runtimeBinPath) {
    return { args: [], env: {} }
  }

  const shellName = basename(options.shell).toLowerCase()
  if (shellName === 'zsh') {
    return {
      args: [],
      env: {
        ZDOTDIR: join(options.startupDir, 'zsh'),
        // Preserve the inherited ZDOTDIR state (present even when empty) so
        // the wrapper zshenv can reproduce the user's native startup files.
        ...(options.env.ZDOTDIR !== undefined
          ? { [userZdotdirEnvVariable]: options.env.ZDOTDIR }
          : {}),
      },
    }
  }
  if (shellName === 'bash') {
    return {
      args: ['--rcfile', join(options.startupDir, 'bash', 'rc')],
      env: {},
    }
  }

  return { args: [], env: {} }
}
